// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AntMessage.proto

package com.github.mxsm.serialization.protobuf;

public final class AntMessage {
  private AntMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_github_mxsm_serialization_protobuf_AntMessagePackage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_github_mxsm_serialization_protobuf_AntMessagePackage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_github_mxsm_serialization_protobuf_Header_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_github_mxsm_serialization_protobuf_Header_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_github_mxsm_serialization_protobuf_Terminal_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_github_mxsm_serialization_protobuf_Terminal_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_github_mxsm_serialization_protobuf_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_github_mxsm_serialization_protobuf_Message_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_github_mxsm_serialization_protobuf_UserMetadata_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_github_mxsm_serialization_protobuf_UserMetadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_github_mxsm_serialization_protobuf_UserMetadata_ExtEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_github_mxsm_serialization_protobuf_UserMetadata_ExtEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_github_mxsm_serialization_protobuf_CtrlMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_github_mxsm_serialization_protobuf_CtrlMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_github_mxsm_serialization_protobuf_AttachmentMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_github_mxsm_serialization_protobuf_AttachmentMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020AntMessage.proto\022&com.github.mxsm.seri" +
      "alization.protobuf\"\213\003\n\021AntMessagePackage" +
      "\022\020\n\010protocol\030\001 \001(\t\022\017\n\007version\030\002 \001(\t\022\021\n\tp" +
      "ackageId\030\003 \001(\003\022\023\n\013packageTime\030\004 \001(\003\022\r\n\005f" +
      "lags\030\005 \001(\005\022>\n\006header\030\006 \001(\0132..com.github." +
      "mxsm.serialization.protobuf.Header\022I\n\014ct" +
      "rlMessages\030\007 \003(\01323.com.github.mxsm.seria" +
      "lization.protobuf.CtrlMessage\022A\n\010message" +
      "s\030\010 \003(\0132/.com.github.mxsm.serialization." +
      "protobuf.Message\022N\n\013attachments\030\t \003(\01329." +
      "com.github.mxsm.serialization.protobuf.A" +
      "ttachmentMessage\"\272\001\n\006Header\022\016\n\006sender\030\001 " +
      "\001(\003\022\020\n\010receiver\030\002 \001(\003\022B\n\010terminal\030\003 \001(\0132" +
      "0.com.github.mxsm.serialization.protobuf" +
      ".Terminal\022J\n\014userMetadata\030\004 \001(\01324.com.gi" +
      "thub.mxsm.serialization.protobuf.UserMet" +
      "adata\"\213\001\n\010Terminal\022F\n\010termType\030\001 \001(\01624.c" +
      "om.github.mxsm.serialization.protobuf.Te" +
      "rminalType\022\022\n\ndeviceType\030\002 \001(\t\022\016\n\006osType" +
      "\030\003 \001(\t\022\023\n\013deviceToken\030\004 \001(\t\"\312\002\n\007Message\022" +
      "\023\n\013messageTime\030\001 \001(\003\022\021\n\tmessageId\030\002 \001(\003\022" +
      "H\n\013messageType\030\003 \001(\01623.com.github.mxsm.s" +
      "erialization.protobuf.MessageType\022V\n\022mes" +
      "sageContentType\030\004 \001(\0162:.com.github.mxsm." +
      "serialization.protobuf.MessageContentTyp" +
      "e\022\021\n\tmediaLink\030\005 \001(\t\022\017\n\007payload\030\006 \001(\014\022\024\n" +
      "\014originalLink\030\007 \001(\t\022\032\n\022quotationMessageI" +
      "d\030\010 \001(\005\022\017\n\007isAsync\030\t \001(\010\022\016\n\006isBurn\030\n \001(\010" +
      "\"\332\001\n\014UserMetadata\022\016\n\006userId\030\001 \001(\003\022\021\n\tuse" +
      "rToken\030\002 \001(\t\022\r\n\005orgId\030\003 \001(\003\022\020\n\010userName\030" +
      "\004 \001(\t\022\016\n\006connId\030\005 \001(\003\022J\n\003ext\030\006 \003(\0132=.com" +
      ".github.mxsm.serialization.protobuf.User" +
      "Metadata.ExtEntry\032*\n\010ExtEntry\022\013\n\003key\030\001 \001" +
      "(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"\262\001\n\013CtrlMessage\022\023\n" +
      "\013messageTime\030\001 \001(\003\022\021\n\tmessageId\030\002 \001(\005\022\025\n" +
      "\rctrlMessageId\030\003 \001(\003\022P\n\017ctrlMessageType\030" +
      "\004 \001(\01627.com.github.mxsm.serialization.pr" +
      "otobuf.CtrlMessageType\022\022\n\nwithCamera\030\007 \001" +
      "(\010\"\245\001\n\021AttachmentMessage\022\023\n\013messageTime\030" +
      "\001 \001(\003\022\021\n\tmessageId\030\002 \001(\003\022\020\n\010fileType\030\005 \001" +
      "(\t\022\020\n\010filename\030\006 \001(\t\022\021\n\tfileTitle\030\007 \001(\t\022" +
      "\020\n\010fileLink\030\010 \001(\t\022\017\n\007payload\030\t \001(\014\022\016\n\006is" +
      "Sync\030\n \001(\010*O\n\014TerminalType\022\013\n\007ANDROID\020\000\022" +
      "\007\n\003IOS\020\001\022\007\n\003WEB\020\002\022\017\n\013DESKTOP_APP\020\003\022\017\n\013TE" +
      "ST_CLIENT\020\004*Z\n\017CtrlMessageType\022\010\n\004CONN\020\000" +
      "\022\t\n\005CLOSE\020\001\022\007\n\003ACK\020\002\022\007\n\003RCV\020\003\022\n\n\006TYPING\020" +
      "\004\022\010\n\004DIAL\020\005\022\n\n\006ANSWER\020\006*\037\n\013MessageType\022\007" +
      "\n\003P2P\020\000\022\007\n\003P2G\020\001*b\n\022MessageContentType\022\r" +
      "\n\tPLAINTEXT\020\000\022\010\n\004HTML\020\001\022\010\n\004JSON\020\002\022\010\n\004YAM" +
      "L\020\003\022\t\n\005IMAGE\020\004\022\t\n\005AUDIO\020\005\022\t\n\005VIDEO\020\006B*\n&" +
      "com.github.mxsm.serialization.protobufP\001" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_github_mxsm_serialization_protobuf_AntMessagePackage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_github_mxsm_serialization_protobuf_AntMessagePackage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_github_mxsm_serialization_protobuf_AntMessagePackage_descriptor,
        new java.lang.String[] { "Protocol", "Version", "PackageId", "PackageTime", "Flags", "Header", "CtrlMessages", "Messages", "Attachments", });
    internal_static_com_github_mxsm_serialization_protobuf_Header_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_github_mxsm_serialization_protobuf_Header_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_github_mxsm_serialization_protobuf_Header_descriptor,
        new java.lang.String[] { "Sender", "Receiver", "Terminal", "UserMetadata", });
    internal_static_com_github_mxsm_serialization_protobuf_Terminal_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_github_mxsm_serialization_protobuf_Terminal_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_github_mxsm_serialization_protobuf_Terminal_descriptor,
        new java.lang.String[] { "TermType", "DeviceType", "OsType", "DeviceToken", });
    internal_static_com_github_mxsm_serialization_protobuf_Message_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_github_mxsm_serialization_protobuf_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_github_mxsm_serialization_protobuf_Message_descriptor,
        new java.lang.String[] { "MessageTime", "MessageId", "MessageType", "MessageContentType", "MediaLink", "Payload", "OriginalLink", "QuotationMessageId", "IsAsync", "IsBurn", });
    internal_static_com_github_mxsm_serialization_protobuf_UserMetadata_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_github_mxsm_serialization_protobuf_UserMetadata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_github_mxsm_serialization_protobuf_UserMetadata_descriptor,
        new java.lang.String[] { "UserId", "UserToken", "OrgId", "UserName", "ConnId", "Ext", });
    internal_static_com_github_mxsm_serialization_protobuf_UserMetadata_ExtEntry_descriptor =
      internal_static_com_github_mxsm_serialization_protobuf_UserMetadata_descriptor.getNestedTypes().get(0);
    internal_static_com_github_mxsm_serialization_protobuf_UserMetadata_ExtEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_github_mxsm_serialization_protobuf_UserMetadata_ExtEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_com_github_mxsm_serialization_protobuf_CtrlMessage_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_github_mxsm_serialization_protobuf_CtrlMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_github_mxsm_serialization_protobuf_CtrlMessage_descriptor,
        new java.lang.String[] { "MessageTime", "MessageId", "CtrlMessageId", "CtrlMessageType", "WithCamera", });
    internal_static_com_github_mxsm_serialization_protobuf_AttachmentMessage_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_github_mxsm_serialization_protobuf_AttachmentMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_github_mxsm_serialization_protobuf_AttachmentMessage_descriptor,
        new java.lang.String[] { "MessageTime", "MessageId", "FileType", "Filename", "FileTitle", "FileLink", "Payload", "IsSync", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
