// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AntMessage.proto

package com.github.mxsm.serialization.protobuf;

public interface AntMessagePackageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.github.mxsm.serialization.protobuf.AntMessagePackage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 协议名称 YZIMP
   * </pre>
   *
   * <code>string protocol = 1;</code>
   * @return The protocol.
   */
  java.lang.String getProtocol();
  /**
   * <pre>
   * 协议名称 YZIMP
   * </pre>
   *
   * <code>string protocol = 1;</code>
   * @return The bytes for protocol.
   */
  com.google.protobuf.ByteString
      getProtocolBytes();

  /**
   * <pre>
   * 协议版本号 2.0
   * </pre>
   *
   * <code>string version = 2;</code>
   * @return The version.
   */
  java.lang.String getVersion();
  /**
   * <pre>
   * 协议版本号 2.0
   * </pre>
   *
   * <code>string version = 2;</code>
   * @return The bytes for version.
   */
  com.google.protobuf.ByteString
      getVersionBytes();

  /**
   * <pre>
   * 消息包序号，对于每个不同的connId，packageId从0开始重新计算-- 暂时没用因为接入其他
   * </pre>
   *
   * <code>int64 packageId = 3;</code>
   * @return The packageId.
   */
  long getPackageId();

  /**
   * <pre>
   * 消息包时间戳
   * </pre>
   *
   * <code>int64 packageTime = 4;</code>
   * @return The packageTime.
   */
  long getPackageTime();

  /**
   * <pre>
   * 消息体置位标记，共4bytes，32bits，从最低位开始置位表示相应的消息体中是否包含内容
   * 目前仅有最低4bit有效，分别从低位至高位代表用户信息、终端信息、控制信息、内容信息和附件信息
   * 示意图：
   * [[0][0][0][0][0][0][0][0] [0][0][0][0][0][0][0][0] [0][0][0][0][0][0][0][0] [0][0][0][Attachment][ImMessage][ImCtrlMessage][terminal][userInfo]]
   * 如发送一个conn消息应该包含用户信息、终端信息、控制信息，不包含内容信息和附件信息，则flags的设置值为：
   * [[0][0][0][0][0][0][0][0] [0][0][0][0][0][0][0][0] [0][0][0][0][0][0][0][0] [0][0][0][0][0][1][1][1]]
   * </pre>
   *
   * <code>int32 flags = 5;</code>
   * @return The flags.
   */
  int getFlags();

  /**
   * <code>.com.github.mxsm.serialization.protobuf.Header header = 6;</code>
   * @return Whether the header field is set.
   */
  boolean hasHeader();
  /**
   * <code>.com.github.mxsm.serialization.protobuf.Header header = 6;</code>
   * @return The header.
   */
  com.github.mxsm.serialization.protobuf.Header getHeader();
  /**
   * <code>.com.github.mxsm.serialization.protobuf.Header header = 6;</code>
   */
  com.github.mxsm.serialization.protobuf.HeaderOrBuilder getHeaderOrBuilder();

  /**
   * <pre>
   * 一个消息包中可发送多条控制消息报文，原则上不应该超过100条
   * </pre>
   *
   * <code>repeated .com.github.mxsm.serialization.protobuf.CtrlMessage ctrlMessages = 7;</code>
   */
  java.util.List<com.github.mxsm.serialization.protobuf.CtrlMessage> 
      getCtrlMessagesList();
  /**
   * <pre>
   * 一个消息包中可发送多条控制消息报文，原则上不应该超过100条
   * </pre>
   *
   * <code>repeated .com.github.mxsm.serialization.protobuf.CtrlMessage ctrlMessages = 7;</code>
   */
  com.github.mxsm.serialization.protobuf.CtrlMessage getCtrlMessages(int index);
  /**
   * <pre>
   * 一个消息包中可发送多条控制消息报文，原则上不应该超过100条
   * </pre>
   *
   * <code>repeated .com.github.mxsm.serialization.protobuf.CtrlMessage ctrlMessages = 7;</code>
   */
  int getCtrlMessagesCount();
  /**
   * <pre>
   * 一个消息包中可发送多条控制消息报文，原则上不应该超过100条
   * </pre>
   *
   * <code>repeated .com.github.mxsm.serialization.protobuf.CtrlMessage ctrlMessages = 7;</code>
   */
  java.util.List<? extends com.github.mxsm.serialization.protobuf.CtrlMessageOrBuilder> 
      getCtrlMessagesOrBuilderList();
  /**
   * <pre>
   * 一个消息包中可发送多条控制消息报文，原则上不应该超过100条
   * </pre>
   *
   * <code>repeated .com.github.mxsm.serialization.protobuf.CtrlMessage ctrlMessages = 7;</code>
   */
  com.github.mxsm.serialization.protobuf.CtrlMessageOrBuilder getCtrlMessagesOrBuilder(
      int index);

  /**
   * <pre>
   * 一个消息包中可发送多条内容消息体，原则上不应该超过100条
   * </pre>
   *
   * <code>repeated .com.github.mxsm.serialization.protobuf.Message messages = 8;</code>
   */
  java.util.List<com.github.mxsm.serialization.protobuf.Message> 
      getMessagesList();
  /**
   * <pre>
   * 一个消息包中可发送多条内容消息体，原则上不应该超过100条
   * </pre>
   *
   * <code>repeated .com.github.mxsm.serialization.protobuf.Message messages = 8;</code>
   */
  com.github.mxsm.serialization.protobuf.Message getMessages(int index);
  /**
   * <pre>
   * 一个消息包中可发送多条内容消息体，原则上不应该超过100条
   * </pre>
   *
   * <code>repeated .com.github.mxsm.serialization.protobuf.Message messages = 8;</code>
   */
  int getMessagesCount();
  /**
   * <pre>
   * 一个消息包中可发送多条内容消息体，原则上不应该超过100条
   * </pre>
   *
   * <code>repeated .com.github.mxsm.serialization.protobuf.Message messages = 8;</code>
   */
  java.util.List<? extends com.github.mxsm.serialization.protobuf.MessageOrBuilder> 
      getMessagesOrBuilderList();
  /**
   * <pre>
   * 一个消息包中可发送多条内容消息体，原则上不应该超过100条
   * </pre>
   *
   * <code>repeated .com.github.mxsm.serialization.protobuf.Message messages = 8;</code>
   */
  com.github.mxsm.serialization.protobuf.MessageOrBuilder getMessagesOrBuilder(
      int index);

  /**
   * <pre>
   * 一个消息包中可发送多个文件附件，原则上不应该超过10个
   * </pre>
   *
   * <code>repeated .com.github.mxsm.serialization.protobuf.AttachmentMessage attachments = 9;</code>
   */
  java.util.List<com.github.mxsm.serialization.protobuf.AttachmentMessage> 
      getAttachmentsList();
  /**
   * <pre>
   * 一个消息包中可发送多个文件附件，原则上不应该超过10个
   * </pre>
   *
   * <code>repeated .com.github.mxsm.serialization.protobuf.AttachmentMessage attachments = 9;</code>
   */
  com.github.mxsm.serialization.protobuf.AttachmentMessage getAttachments(int index);
  /**
   * <pre>
   * 一个消息包中可发送多个文件附件，原则上不应该超过10个
   * </pre>
   *
   * <code>repeated .com.github.mxsm.serialization.protobuf.AttachmentMessage attachments = 9;</code>
   */
  int getAttachmentsCount();
  /**
   * <pre>
   * 一个消息包中可发送多个文件附件，原则上不应该超过10个
   * </pre>
   *
   * <code>repeated .com.github.mxsm.serialization.protobuf.AttachmentMessage attachments = 9;</code>
   */
  java.util.List<? extends com.github.mxsm.serialization.protobuf.AttachmentMessageOrBuilder> 
      getAttachmentsOrBuilderList();
  /**
   * <pre>
   * 一个消息包中可发送多个文件附件，原则上不应该超过10个
   * </pre>
   *
   * <code>repeated .com.github.mxsm.serialization.protobuf.AttachmentMessage attachments = 9;</code>
   */
  com.github.mxsm.serialization.protobuf.AttachmentMessageOrBuilder getAttachmentsOrBuilder(
      int index);
}
