// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AntMessage.proto

package com.github.mxsm.serialization.protobuf;

/**
 * <pre>
 *附件报文
 * </pre>
 *
 * Protobuf type {@code com.github.mxsm.serialization.protobuf.AttachmentMessage}
 */
public final class AttachmentMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.github.mxsm.serialization.protobuf.AttachmentMessage)
    AttachmentMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AttachmentMessage.newBuilder() to construct.
  private AttachmentMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AttachmentMessage() {
    fileType_ = "";
    filename_ = "";
    fileTitle_ = "";
    fileLink_ = "";
    payload_ = com.google.protobuf.ByteString.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new AttachmentMessage();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AttachmentMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            messageTime_ = input.readInt64();
            break;
          }
          case 16: {

            messageId_ = input.readInt64();
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            fileType_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            filename_ = s;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            fileTitle_ = s;
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            fileLink_ = s;
            break;
          }
          case 74: {

            payload_ = input.readBytes();
            break;
          }
          case 80: {

            isSync_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.github.mxsm.serialization.protobuf.AntMessage.internal_static_com_github_mxsm_serialization_protobuf_AttachmentMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.github.mxsm.serialization.protobuf.AntMessage.internal_static_com_github_mxsm_serialization_protobuf_AttachmentMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.github.mxsm.serialization.protobuf.AttachmentMessage.class, com.github.mxsm.serialization.protobuf.AttachmentMessage.Builder.class);
  }

  public static final int MESSAGETIME_FIELD_NUMBER = 1;
  private long messageTime_;
  /**
   * <pre>
   * 消息报文时间戳
   * </pre>
   *
   * <code>int64 messageTime = 1;</code>
   * @return The messageTime.
   */
  @java.lang.Override
  public long getMessageTime() {
    return messageTime_;
  }

  public static final int MESSAGEID_FIELD_NUMBER = 2;
  private long messageId_;
  /**
   * <pre>
   * 消息报文ID，在同一次socket连接过程中保证唯一，即connId不变的情况下，该ID递增
   * </pre>
   *
   * <code>int64 messageId = 2;</code>
   * @return The messageId.
   */
  @java.lang.Override
  public long getMessageId() {
    return messageId_;
  }

  public static final int FILETYPE_FIELD_NUMBER = 5;
  private volatile java.lang.Object fileType_;
  /**
   * <pre>
   * 文件附件类型，如docx, pdf, xlsx等
   * </pre>
   *
   * <code>string fileType = 5;</code>
   * @return The fileType.
   */
  @java.lang.Override
  public java.lang.String getFileType() {
    java.lang.Object ref = fileType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      fileType_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 文件附件类型，如docx, pdf, xlsx等
   * </pre>
   *
   * <code>string fileType = 5;</code>
   * @return The bytes for fileType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFileTypeBytes() {
    java.lang.Object ref = fileType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      fileType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FILENAME_FIELD_NUMBER = 6;
  private volatile java.lang.Object filename_;
  /**
   * <pre>
   * 文件附件名称，如xxx.pdf等
   * </pre>
   *
   * <code>string filename = 6;</code>
   * @return The filename.
   */
  @java.lang.Override
  public java.lang.String getFilename() {
    java.lang.Object ref = filename_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      filename_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 文件附件名称，如xxx.pdf等
   * </pre>
   *
   * <code>string filename = 6;</code>
   * @return The bytes for filename.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFilenameBytes() {
    java.lang.Object ref = filename_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      filename_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FILETITLE_FIELD_NUMBER = 7;
  private volatile java.lang.Object fileTitle_;
  /**
   * <pre>
   * 文件附件标题
   * </pre>
   *
   * <code>string fileTitle = 7;</code>
   * @return The fileTitle.
   */
  @java.lang.Override
  public java.lang.String getFileTitle() {
    java.lang.Object ref = fileTitle_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      fileTitle_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 文件附件标题
   * </pre>
   *
   * <code>string fileTitle = 7;</code>
   * @return The bytes for fileTitle.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFileTitleBytes() {
    java.lang.Object ref = fileTitle_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      fileTitle_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FILELINK_FIELD_NUMBER = 8;
  private volatile java.lang.Object fileLink_;
  /**
   * <pre>
   * 文件附件链接URL地址
   * </pre>
   *
   * <code>string fileLink = 8;</code>
   * @return The fileLink.
   */
  @java.lang.Override
  public java.lang.String getFileLink() {
    java.lang.Object ref = fileLink_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      fileLink_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 文件附件链接URL地址
   * </pre>
   *
   * <code>string fileLink = 8;</code>
   * @return The bytes for fileLink.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFileLinkBytes() {
    java.lang.Object ref = fileLink_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      fileLink_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PAYLOAD_FIELD_NUMBER = 9;
  private com.google.protobuf.ByteString payload_;
  /**
   * <pre>
   * 发送时文件二进制内容，接收时该字段为空
   * </pre>
   *
   * <code>bytes payload = 9;</code>
   * @return The payload.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getPayload() {
    return payload_;
  }

  public static final int ISSYNC_FIELD_NUMBER = 10;
  private boolean isSync_;
  /**
   * <pre>
   * 是否为多端同步消息标志
   * </pre>
   *
   * <code>bool isSync = 10;</code>
   * @return The isSync.
   */
  @java.lang.Override
  public boolean getIsSync() {
    return isSync_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (messageTime_ != 0L) {
      output.writeInt64(1, messageTime_);
    }
    if (messageId_ != 0L) {
      output.writeInt64(2, messageId_);
    }
    if (!getFileTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, fileType_);
    }
    if (!getFilenameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, filename_);
    }
    if (!getFileTitleBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, fileTitle_);
    }
    if (!getFileLinkBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, fileLink_);
    }
    if (!payload_.isEmpty()) {
      output.writeBytes(9, payload_);
    }
    if (isSync_ != false) {
      output.writeBool(10, isSync_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (messageTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, messageTime_);
    }
    if (messageId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, messageId_);
    }
    if (!getFileTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, fileType_);
    }
    if (!getFilenameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, filename_);
    }
    if (!getFileTitleBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, fileTitle_);
    }
    if (!getFileLinkBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, fileLink_);
    }
    if (!payload_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(9, payload_);
    }
    if (isSync_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(10, isSync_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.github.mxsm.serialization.protobuf.AttachmentMessage)) {
      return super.equals(obj);
    }
    com.github.mxsm.serialization.protobuf.AttachmentMessage other = (com.github.mxsm.serialization.protobuf.AttachmentMessage) obj;

    if (getMessageTime()
        != other.getMessageTime()) return false;
    if (getMessageId()
        != other.getMessageId()) return false;
    if (!getFileType()
        .equals(other.getFileType())) return false;
    if (!getFilename()
        .equals(other.getFilename())) return false;
    if (!getFileTitle()
        .equals(other.getFileTitle())) return false;
    if (!getFileLink()
        .equals(other.getFileLink())) return false;
    if (!getPayload()
        .equals(other.getPayload())) return false;
    if (getIsSync()
        != other.getIsSync()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MESSAGETIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getMessageTime());
    hash = (37 * hash) + MESSAGEID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getMessageId());
    hash = (37 * hash) + FILETYPE_FIELD_NUMBER;
    hash = (53 * hash) + getFileType().hashCode();
    hash = (37 * hash) + FILENAME_FIELD_NUMBER;
    hash = (53 * hash) + getFilename().hashCode();
    hash = (37 * hash) + FILETITLE_FIELD_NUMBER;
    hash = (53 * hash) + getFileTitle().hashCode();
    hash = (37 * hash) + FILELINK_FIELD_NUMBER;
    hash = (53 * hash) + getFileLink().hashCode();
    hash = (37 * hash) + PAYLOAD_FIELD_NUMBER;
    hash = (53 * hash) + getPayload().hashCode();
    hash = (37 * hash) + ISSYNC_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsSync());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.github.mxsm.serialization.protobuf.AttachmentMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.mxsm.serialization.protobuf.AttachmentMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.mxsm.serialization.protobuf.AttachmentMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.mxsm.serialization.protobuf.AttachmentMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.mxsm.serialization.protobuf.AttachmentMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.mxsm.serialization.protobuf.AttachmentMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.mxsm.serialization.protobuf.AttachmentMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.mxsm.serialization.protobuf.AttachmentMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.mxsm.serialization.protobuf.AttachmentMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.github.mxsm.serialization.protobuf.AttachmentMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.mxsm.serialization.protobuf.AttachmentMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.mxsm.serialization.protobuf.AttachmentMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.github.mxsm.serialization.protobuf.AttachmentMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *附件报文
   * </pre>
   *
   * Protobuf type {@code com.github.mxsm.serialization.protobuf.AttachmentMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.github.mxsm.serialization.protobuf.AttachmentMessage)
      com.github.mxsm.serialization.protobuf.AttachmentMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.mxsm.serialization.protobuf.AntMessage.internal_static_com_github_mxsm_serialization_protobuf_AttachmentMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.mxsm.serialization.protobuf.AntMessage.internal_static_com_github_mxsm_serialization_protobuf_AttachmentMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.mxsm.serialization.protobuf.AttachmentMessage.class, com.github.mxsm.serialization.protobuf.AttachmentMessage.Builder.class);
    }

    // Construct using com.github.mxsm.serialization.protobuf.AttachmentMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      messageTime_ = 0L;

      messageId_ = 0L;

      fileType_ = "";

      filename_ = "";

      fileTitle_ = "";

      fileLink_ = "";

      payload_ = com.google.protobuf.ByteString.EMPTY;

      isSync_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.github.mxsm.serialization.protobuf.AntMessage.internal_static_com_github_mxsm_serialization_protobuf_AttachmentMessage_descriptor;
    }

    @java.lang.Override
    public com.github.mxsm.serialization.protobuf.AttachmentMessage getDefaultInstanceForType() {
      return com.github.mxsm.serialization.protobuf.AttachmentMessage.getDefaultInstance();
    }

    @java.lang.Override
    public com.github.mxsm.serialization.protobuf.AttachmentMessage build() {
      com.github.mxsm.serialization.protobuf.AttachmentMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.github.mxsm.serialization.protobuf.AttachmentMessage buildPartial() {
      com.github.mxsm.serialization.protobuf.AttachmentMessage result = new com.github.mxsm.serialization.protobuf.AttachmentMessage(this);
      result.messageTime_ = messageTime_;
      result.messageId_ = messageId_;
      result.fileType_ = fileType_;
      result.filename_ = filename_;
      result.fileTitle_ = fileTitle_;
      result.fileLink_ = fileLink_;
      result.payload_ = payload_;
      result.isSync_ = isSync_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.github.mxsm.serialization.protobuf.AttachmentMessage) {
        return mergeFrom((com.github.mxsm.serialization.protobuf.AttachmentMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.github.mxsm.serialization.protobuf.AttachmentMessage other) {
      if (other == com.github.mxsm.serialization.protobuf.AttachmentMessage.getDefaultInstance()) return this;
      if (other.getMessageTime() != 0L) {
        setMessageTime(other.getMessageTime());
      }
      if (other.getMessageId() != 0L) {
        setMessageId(other.getMessageId());
      }
      if (!other.getFileType().isEmpty()) {
        fileType_ = other.fileType_;
        onChanged();
      }
      if (!other.getFilename().isEmpty()) {
        filename_ = other.filename_;
        onChanged();
      }
      if (!other.getFileTitle().isEmpty()) {
        fileTitle_ = other.fileTitle_;
        onChanged();
      }
      if (!other.getFileLink().isEmpty()) {
        fileLink_ = other.fileLink_;
        onChanged();
      }
      if (other.getPayload() != com.google.protobuf.ByteString.EMPTY) {
        setPayload(other.getPayload());
      }
      if (other.getIsSync() != false) {
        setIsSync(other.getIsSync());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.github.mxsm.serialization.protobuf.AttachmentMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.github.mxsm.serialization.protobuf.AttachmentMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long messageTime_ ;
    /**
     * <pre>
     * 消息报文时间戳
     * </pre>
     *
     * <code>int64 messageTime = 1;</code>
     * @return The messageTime.
     */
    @java.lang.Override
    public long getMessageTime() {
      return messageTime_;
    }
    /**
     * <pre>
     * 消息报文时间戳
     * </pre>
     *
     * <code>int64 messageTime = 1;</code>
     * @param value The messageTime to set.
     * @return This builder for chaining.
     */
    public Builder setMessageTime(long value) {
      
      messageTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 消息报文时间戳
     * </pre>
     *
     * <code>int64 messageTime = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMessageTime() {
      
      messageTime_ = 0L;
      onChanged();
      return this;
    }

    private long messageId_ ;
    /**
     * <pre>
     * 消息报文ID，在同一次socket连接过程中保证唯一，即connId不变的情况下，该ID递增
     * </pre>
     *
     * <code>int64 messageId = 2;</code>
     * @return The messageId.
     */
    @java.lang.Override
    public long getMessageId() {
      return messageId_;
    }
    /**
     * <pre>
     * 消息报文ID，在同一次socket连接过程中保证唯一，即connId不变的情况下，该ID递增
     * </pre>
     *
     * <code>int64 messageId = 2;</code>
     * @param value The messageId to set.
     * @return This builder for chaining.
     */
    public Builder setMessageId(long value) {
      
      messageId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 消息报文ID，在同一次socket连接过程中保证唯一，即connId不变的情况下，该ID递增
     * </pre>
     *
     * <code>int64 messageId = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearMessageId() {
      
      messageId_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object fileType_ = "";
    /**
     * <pre>
     * 文件附件类型，如docx, pdf, xlsx等
     * </pre>
     *
     * <code>string fileType = 5;</code>
     * @return The fileType.
     */
    public java.lang.String getFileType() {
      java.lang.Object ref = fileType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fileType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 文件附件类型，如docx, pdf, xlsx等
     * </pre>
     *
     * <code>string fileType = 5;</code>
     * @return The bytes for fileType.
     */
    public com.google.protobuf.ByteString
        getFileTypeBytes() {
      java.lang.Object ref = fileType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fileType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 文件附件类型，如docx, pdf, xlsx等
     * </pre>
     *
     * <code>string fileType = 5;</code>
     * @param value The fileType to set.
     * @return This builder for chaining.
     */
    public Builder setFileType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      fileType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 文件附件类型，如docx, pdf, xlsx等
     * </pre>
     *
     * <code>string fileType = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearFileType() {
      
      fileType_ = getDefaultInstance().getFileType();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 文件附件类型，如docx, pdf, xlsx等
     * </pre>
     *
     * <code>string fileType = 5;</code>
     * @param value The bytes for fileType to set.
     * @return This builder for chaining.
     */
    public Builder setFileTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      fileType_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object filename_ = "";
    /**
     * <pre>
     * 文件附件名称，如xxx.pdf等
     * </pre>
     *
     * <code>string filename = 6;</code>
     * @return The filename.
     */
    public java.lang.String getFilename() {
      java.lang.Object ref = filename_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        filename_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 文件附件名称，如xxx.pdf等
     * </pre>
     *
     * <code>string filename = 6;</code>
     * @return The bytes for filename.
     */
    public com.google.protobuf.ByteString
        getFilenameBytes() {
      java.lang.Object ref = filename_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        filename_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 文件附件名称，如xxx.pdf等
     * </pre>
     *
     * <code>string filename = 6;</code>
     * @param value The filename to set.
     * @return This builder for chaining.
     */
    public Builder setFilename(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      filename_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 文件附件名称，如xxx.pdf等
     * </pre>
     *
     * <code>string filename = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearFilename() {
      
      filename_ = getDefaultInstance().getFilename();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 文件附件名称，如xxx.pdf等
     * </pre>
     *
     * <code>string filename = 6;</code>
     * @param value The bytes for filename to set.
     * @return This builder for chaining.
     */
    public Builder setFilenameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      filename_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object fileTitle_ = "";
    /**
     * <pre>
     * 文件附件标题
     * </pre>
     *
     * <code>string fileTitle = 7;</code>
     * @return The fileTitle.
     */
    public java.lang.String getFileTitle() {
      java.lang.Object ref = fileTitle_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fileTitle_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 文件附件标题
     * </pre>
     *
     * <code>string fileTitle = 7;</code>
     * @return The bytes for fileTitle.
     */
    public com.google.protobuf.ByteString
        getFileTitleBytes() {
      java.lang.Object ref = fileTitle_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fileTitle_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 文件附件标题
     * </pre>
     *
     * <code>string fileTitle = 7;</code>
     * @param value The fileTitle to set.
     * @return This builder for chaining.
     */
    public Builder setFileTitle(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      fileTitle_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 文件附件标题
     * </pre>
     *
     * <code>string fileTitle = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearFileTitle() {
      
      fileTitle_ = getDefaultInstance().getFileTitle();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 文件附件标题
     * </pre>
     *
     * <code>string fileTitle = 7;</code>
     * @param value The bytes for fileTitle to set.
     * @return This builder for chaining.
     */
    public Builder setFileTitleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      fileTitle_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object fileLink_ = "";
    /**
     * <pre>
     * 文件附件链接URL地址
     * </pre>
     *
     * <code>string fileLink = 8;</code>
     * @return The fileLink.
     */
    public java.lang.String getFileLink() {
      java.lang.Object ref = fileLink_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fileLink_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 文件附件链接URL地址
     * </pre>
     *
     * <code>string fileLink = 8;</code>
     * @return The bytes for fileLink.
     */
    public com.google.protobuf.ByteString
        getFileLinkBytes() {
      java.lang.Object ref = fileLink_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fileLink_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 文件附件链接URL地址
     * </pre>
     *
     * <code>string fileLink = 8;</code>
     * @param value The fileLink to set.
     * @return This builder for chaining.
     */
    public Builder setFileLink(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      fileLink_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 文件附件链接URL地址
     * </pre>
     *
     * <code>string fileLink = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearFileLink() {
      
      fileLink_ = getDefaultInstance().getFileLink();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 文件附件链接URL地址
     * </pre>
     *
     * <code>string fileLink = 8;</code>
     * @param value The bytes for fileLink to set.
     * @return This builder for chaining.
     */
    public Builder setFileLinkBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      fileLink_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * 发送时文件二进制内容，接收时该字段为空
     * </pre>
     *
     * <code>bytes payload = 9;</code>
     * @return The payload.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getPayload() {
      return payload_;
    }
    /**
     * <pre>
     * 发送时文件二进制内容，接收时该字段为空
     * </pre>
     *
     * <code>bytes payload = 9;</code>
     * @param value The payload to set.
     * @return This builder for chaining.
     */
    public Builder setPayload(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      payload_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 发送时文件二进制内容，接收时该字段为空
     * </pre>
     *
     * <code>bytes payload = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearPayload() {
      
      payload_ = getDefaultInstance().getPayload();
      onChanged();
      return this;
    }

    private boolean isSync_ ;
    /**
     * <pre>
     * 是否为多端同步消息标志
     * </pre>
     *
     * <code>bool isSync = 10;</code>
     * @return The isSync.
     */
    @java.lang.Override
    public boolean getIsSync() {
      return isSync_;
    }
    /**
     * <pre>
     * 是否为多端同步消息标志
     * </pre>
     *
     * <code>bool isSync = 10;</code>
     * @param value The isSync to set.
     * @return This builder for chaining.
     */
    public Builder setIsSync(boolean value) {
      
      isSync_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 是否为多端同步消息标志
     * </pre>
     *
     * <code>bool isSync = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsSync() {
      
      isSync_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.github.mxsm.serialization.protobuf.AttachmentMessage)
  }

  // @@protoc_insertion_point(class_scope:com.github.mxsm.serialization.protobuf.AttachmentMessage)
  private static final com.github.mxsm.serialization.protobuf.AttachmentMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.github.mxsm.serialization.protobuf.AttachmentMessage();
  }

  public static com.github.mxsm.serialization.protobuf.AttachmentMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AttachmentMessage>
      PARSER = new com.google.protobuf.AbstractParser<AttachmentMessage>() {
    @java.lang.Override
    public AttachmentMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AttachmentMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AttachmentMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AttachmentMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.github.mxsm.serialization.protobuf.AttachmentMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

