// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AntMessage.proto

package com.github.mxsm.serialization.protobuf;

public interface AttachmentMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.github.mxsm.serialization.protobuf.AttachmentMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 消息报文时间戳
   * </pre>
   *
   * <code>int64 messageTime = 1;</code>
   * @return The messageTime.
   */
  long getMessageTime();

  /**
   * <pre>
   * 消息报文ID，在同一次socket连接过程中保证唯一，即connId不变的情况下，该ID递增
   * </pre>
   *
   * <code>int64 messageId = 2;</code>
   * @return The messageId.
   */
  long getMessageId();

  /**
   * <pre>
   * 文件附件类型，如docx, pdf, xlsx等
   * </pre>
   *
   * <code>string fileType = 5;</code>
   * @return The fileType.
   */
  java.lang.String getFileType();
  /**
   * <pre>
   * 文件附件类型，如docx, pdf, xlsx等
   * </pre>
   *
   * <code>string fileType = 5;</code>
   * @return The bytes for fileType.
   */
  com.google.protobuf.ByteString
      getFileTypeBytes();

  /**
   * <pre>
   * 文件附件名称，如xxx.pdf等
   * </pre>
   *
   * <code>string filename = 6;</code>
   * @return The filename.
   */
  java.lang.String getFilename();
  /**
   * <pre>
   * 文件附件名称，如xxx.pdf等
   * </pre>
   *
   * <code>string filename = 6;</code>
   * @return The bytes for filename.
   */
  com.google.protobuf.ByteString
      getFilenameBytes();

  /**
   * <pre>
   * 文件附件标题
   * </pre>
   *
   * <code>string fileTitle = 7;</code>
   * @return The fileTitle.
   */
  java.lang.String getFileTitle();
  /**
   * <pre>
   * 文件附件标题
   * </pre>
   *
   * <code>string fileTitle = 7;</code>
   * @return The bytes for fileTitle.
   */
  com.google.protobuf.ByteString
      getFileTitleBytes();

  /**
   * <pre>
   * 文件附件链接URL地址
   * </pre>
   *
   * <code>string fileLink = 8;</code>
   * @return The fileLink.
   */
  java.lang.String getFileLink();
  /**
   * <pre>
   * 文件附件链接URL地址
   * </pre>
   *
   * <code>string fileLink = 8;</code>
   * @return The bytes for fileLink.
   */
  com.google.protobuf.ByteString
      getFileLinkBytes();

  /**
   * <pre>
   * 发送时文件二进制内容，接收时该字段为空
   * </pre>
   *
   * <code>bytes payload = 9;</code>
   * @return The payload.
   */
  com.google.protobuf.ByteString getPayload();

  /**
   * <pre>
   * 是否为多端同步消息标志
   * </pre>
   *
   * <code>bool isSync = 10;</code>
   * @return The isSync.
   */
  boolean getIsSync();
}
