// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AntMessage.proto

package com.github.mxsm.serialization.protobuf;

/**
 * <pre>
 * 控制信息消息体
 * </pre>
 *
 * Protobuf type {@code com.github.mxsm.serialization.protobuf.CtrlMessage}
 */
public final class CtrlMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.github.mxsm.serialization.protobuf.CtrlMessage)
    CtrlMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CtrlMessage.newBuilder() to construct.
  private CtrlMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CtrlMessage() {
    ctrlMessageType_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CtrlMessage();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CtrlMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            messageTime_ = input.readInt64();
            break;
          }
          case 16: {

            messageId_ = input.readInt32();
            break;
          }
          case 24: {

            ctrlMessageId_ = input.readInt64();
            break;
          }
          case 32: {
            int rawValue = input.readEnum();

            ctrlMessageType_ = rawValue;
            break;
          }
          case 56: {

            withCamera_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.github.mxsm.serialization.protobuf.AntMessage.internal_static_com_github_mxsm_serialization_protobuf_CtrlMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.github.mxsm.serialization.protobuf.AntMessage.internal_static_com_github_mxsm_serialization_protobuf_CtrlMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.github.mxsm.serialization.protobuf.CtrlMessage.class, com.github.mxsm.serialization.protobuf.CtrlMessage.Builder.class);
  }

  public static final int MESSAGETIME_FIELD_NUMBER = 1;
  private long messageTime_;
  /**
   * <pre>
   * 消息报文时间戳
   * </pre>
   *
   * <code>int64 messageTime = 1;</code>
   * @return The messageTime.
   */
  @java.lang.Override
  public long getMessageTime() {
    return messageTime_;
  }

  public static final int MESSAGEID_FIELD_NUMBER = 2;
  private int messageId_;
  /**
   * <pre>
   * 消息报文ID，在同一次socket连接过程中保证唯一，即connId不变的情况下，该ID递增
   * </pre>
   *
   * <code>int32 messageId = 2;</code>
   * @return The messageId.
   */
  @java.lang.Override
  public int getMessageId() {
    return messageId_;
  }

  public static final int CTRLMESSAGEID_FIELD_NUMBER = 3;
  private long ctrlMessageId_;
  /**
   * <pre>
   * 控制消息报文ID
   * </pre>
   *
   * <code>int64 ctrlMessageId = 3;</code>
   * @return The ctrlMessageId.
   */
  @java.lang.Override
  public long getCtrlMessageId() {
    return ctrlMessageId_;
  }

  public static final int CTRLMESSAGETYPE_FIELD_NUMBER = 4;
  private int ctrlMessageType_;
  /**
   * <pre>
   * 控制消息类型
   * </pre>
   *
   * <code>.com.github.mxsm.serialization.protobuf.CtrlMessageType ctrlMessageType = 4;</code>
   * @return The enum numeric value on the wire for ctrlMessageType.
   */
  @java.lang.Override public int getCtrlMessageTypeValue() {
    return ctrlMessageType_;
  }
  /**
   * <pre>
   * 控制消息类型
   * </pre>
   *
   * <code>.com.github.mxsm.serialization.protobuf.CtrlMessageType ctrlMessageType = 4;</code>
   * @return The ctrlMessageType.
   */
  @java.lang.Override public com.github.mxsm.serialization.protobuf.CtrlMessageType getCtrlMessageType() {
    @SuppressWarnings("deprecation")
    com.github.mxsm.serialization.protobuf.CtrlMessageType result = com.github.mxsm.serialization.protobuf.CtrlMessageType.valueOf(ctrlMessageType_);
    return result == null ? com.github.mxsm.serialization.protobuf.CtrlMessageType.UNRECOGNIZED : result;
  }

  public static final int WITHCAMERA_FIELD_NUMBER = 7;
  private boolean withCamera_;
  /**
   * <pre>
   * 拨号接听类型中是否使用视频聊天功能标志
   * </pre>
   *
   * <code>bool withCamera = 7;</code>
   * @return The withCamera.
   */
  @java.lang.Override
  public boolean getWithCamera() {
    return withCamera_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (messageTime_ != 0L) {
      output.writeInt64(1, messageTime_);
    }
    if (messageId_ != 0) {
      output.writeInt32(2, messageId_);
    }
    if (ctrlMessageId_ != 0L) {
      output.writeInt64(3, ctrlMessageId_);
    }
    if (ctrlMessageType_ != com.github.mxsm.serialization.protobuf.CtrlMessageType.CONN.getNumber()) {
      output.writeEnum(4, ctrlMessageType_);
    }
    if (withCamera_ != false) {
      output.writeBool(7, withCamera_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (messageTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, messageTime_);
    }
    if (messageId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, messageId_);
    }
    if (ctrlMessageId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, ctrlMessageId_);
    }
    if (ctrlMessageType_ != com.github.mxsm.serialization.protobuf.CtrlMessageType.CONN.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, ctrlMessageType_);
    }
    if (withCamera_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(7, withCamera_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.github.mxsm.serialization.protobuf.CtrlMessage)) {
      return super.equals(obj);
    }
    com.github.mxsm.serialization.protobuf.CtrlMessage other = (com.github.mxsm.serialization.protobuf.CtrlMessage) obj;

    if (getMessageTime()
        != other.getMessageTime()) return false;
    if (getMessageId()
        != other.getMessageId()) return false;
    if (getCtrlMessageId()
        != other.getCtrlMessageId()) return false;
    if (ctrlMessageType_ != other.ctrlMessageType_) return false;
    if (getWithCamera()
        != other.getWithCamera()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MESSAGETIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getMessageTime());
    hash = (37 * hash) + MESSAGEID_FIELD_NUMBER;
    hash = (53 * hash) + getMessageId();
    hash = (37 * hash) + CTRLMESSAGEID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCtrlMessageId());
    hash = (37 * hash) + CTRLMESSAGETYPE_FIELD_NUMBER;
    hash = (53 * hash) + ctrlMessageType_;
    hash = (37 * hash) + WITHCAMERA_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getWithCamera());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.github.mxsm.serialization.protobuf.CtrlMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.mxsm.serialization.protobuf.CtrlMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.mxsm.serialization.protobuf.CtrlMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.mxsm.serialization.protobuf.CtrlMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.mxsm.serialization.protobuf.CtrlMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.mxsm.serialization.protobuf.CtrlMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.mxsm.serialization.protobuf.CtrlMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.mxsm.serialization.protobuf.CtrlMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.mxsm.serialization.protobuf.CtrlMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.github.mxsm.serialization.protobuf.CtrlMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.mxsm.serialization.protobuf.CtrlMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.mxsm.serialization.protobuf.CtrlMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.github.mxsm.serialization.protobuf.CtrlMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 控制信息消息体
   * </pre>
   *
   * Protobuf type {@code com.github.mxsm.serialization.protobuf.CtrlMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.github.mxsm.serialization.protobuf.CtrlMessage)
      com.github.mxsm.serialization.protobuf.CtrlMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.mxsm.serialization.protobuf.AntMessage.internal_static_com_github_mxsm_serialization_protobuf_CtrlMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.mxsm.serialization.protobuf.AntMessage.internal_static_com_github_mxsm_serialization_protobuf_CtrlMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.mxsm.serialization.protobuf.CtrlMessage.class, com.github.mxsm.serialization.protobuf.CtrlMessage.Builder.class);
    }

    // Construct using com.github.mxsm.serialization.protobuf.CtrlMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      messageTime_ = 0L;

      messageId_ = 0;

      ctrlMessageId_ = 0L;

      ctrlMessageType_ = 0;

      withCamera_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.github.mxsm.serialization.protobuf.AntMessage.internal_static_com_github_mxsm_serialization_protobuf_CtrlMessage_descriptor;
    }

    @java.lang.Override
    public com.github.mxsm.serialization.protobuf.CtrlMessage getDefaultInstanceForType() {
      return com.github.mxsm.serialization.protobuf.CtrlMessage.getDefaultInstance();
    }

    @java.lang.Override
    public com.github.mxsm.serialization.protobuf.CtrlMessage build() {
      com.github.mxsm.serialization.protobuf.CtrlMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.github.mxsm.serialization.protobuf.CtrlMessage buildPartial() {
      com.github.mxsm.serialization.protobuf.CtrlMessage result = new com.github.mxsm.serialization.protobuf.CtrlMessage(this);
      result.messageTime_ = messageTime_;
      result.messageId_ = messageId_;
      result.ctrlMessageId_ = ctrlMessageId_;
      result.ctrlMessageType_ = ctrlMessageType_;
      result.withCamera_ = withCamera_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.github.mxsm.serialization.protobuf.CtrlMessage) {
        return mergeFrom((com.github.mxsm.serialization.protobuf.CtrlMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.github.mxsm.serialization.protobuf.CtrlMessage other) {
      if (other == com.github.mxsm.serialization.protobuf.CtrlMessage.getDefaultInstance()) return this;
      if (other.getMessageTime() != 0L) {
        setMessageTime(other.getMessageTime());
      }
      if (other.getMessageId() != 0) {
        setMessageId(other.getMessageId());
      }
      if (other.getCtrlMessageId() != 0L) {
        setCtrlMessageId(other.getCtrlMessageId());
      }
      if (other.ctrlMessageType_ != 0) {
        setCtrlMessageTypeValue(other.getCtrlMessageTypeValue());
      }
      if (other.getWithCamera() != false) {
        setWithCamera(other.getWithCamera());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.github.mxsm.serialization.protobuf.CtrlMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.github.mxsm.serialization.protobuf.CtrlMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long messageTime_ ;
    /**
     * <pre>
     * 消息报文时间戳
     * </pre>
     *
     * <code>int64 messageTime = 1;</code>
     * @return The messageTime.
     */
    @java.lang.Override
    public long getMessageTime() {
      return messageTime_;
    }
    /**
     * <pre>
     * 消息报文时间戳
     * </pre>
     *
     * <code>int64 messageTime = 1;</code>
     * @param value The messageTime to set.
     * @return This builder for chaining.
     */
    public Builder setMessageTime(long value) {
      
      messageTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 消息报文时间戳
     * </pre>
     *
     * <code>int64 messageTime = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMessageTime() {
      
      messageTime_ = 0L;
      onChanged();
      return this;
    }

    private int messageId_ ;
    /**
     * <pre>
     * 消息报文ID，在同一次socket连接过程中保证唯一，即connId不变的情况下，该ID递增
     * </pre>
     *
     * <code>int32 messageId = 2;</code>
     * @return The messageId.
     */
    @java.lang.Override
    public int getMessageId() {
      return messageId_;
    }
    /**
     * <pre>
     * 消息报文ID，在同一次socket连接过程中保证唯一，即connId不变的情况下，该ID递增
     * </pre>
     *
     * <code>int32 messageId = 2;</code>
     * @param value The messageId to set.
     * @return This builder for chaining.
     */
    public Builder setMessageId(int value) {
      
      messageId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 消息报文ID，在同一次socket连接过程中保证唯一，即connId不变的情况下，该ID递增
     * </pre>
     *
     * <code>int32 messageId = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearMessageId() {
      
      messageId_ = 0;
      onChanged();
      return this;
    }

    private long ctrlMessageId_ ;
    /**
     * <pre>
     * 控制消息报文ID
     * </pre>
     *
     * <code>int64 ctrlMessageId = 3;</code>
     * @return The ctrlMessageId.
     */
    @java.lang.Override
    public long getCtrlMessageId() {
      return ctrlMessageId_;
    }
    /**
     * <pre>
     * 控制消息报文ID
     * </pre>
     *
     * <code>int64 ctrlMessageId = 3;</code>
     * @param value The ctrlMessageId to set.
     * @return This builder for chaining.
     */
    public Builder setCtrlMessageId(long value) {
      
      ctrlMessageId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 控制消息报文ID
     * </pre>
     *
     * <code>int64 ctrlMessageId = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearCtrlMessageId() {
      
      ctrlMessageId_ = 0L;
      onChanged();
      return this;
    }

    private int ctrlMessageType_ = 0;
    /**
     * <pre>
     * 控制消息类型
     * </pre>
     *
     * <code>.com.github.mxsm.serialization.protobuf.CtrlMessageType ctrlMessageType = 4;</code>
     * @return The enum numeric value on the wire for ctrlMessageType.
     */
    @java.lang.Override public int getCtrlMessageTypeValue() {
      return ctrlMessageType_;
    }
    /**
     * <pre>
     * 控制消息类型
     * </pre>
     *
     * <code>.com.github.mxsm.serialization.protobuf.CtrlMessageType ctrlMessageType = 4;</code>
     * @param value The enum numeric value on the wire for ctrlMessageType to set.
     * @return This builder for chaining.
     */
    public Builder setCtrlMessageTypeValue(int value) {
      
      ctrlMessageType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 控制消息类型
     * </pre>
     *
     * <code>.com.github.mxsm.serialization.protobuf.CtrlMessageType ctrlMessageType = 4;</code>
     * @return The ctrlMessageType.
     */
    @java.lang.Override
    public com.github.mxsm.serialization.protobuf.CtrlMessageType getCtrlMessageType() {
      @SuppressWarnings("deprecation")
      com.github.mxsm.serialization.protobuf.CtrlMessageType result = com.github.mxsm.serialization.protobuf.CtrlMessageType.valueOf(ctrlMessageType_);
      return result == null ? com.github.mxsm.serialization.protobuf.CtrlMessageType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * 控制消息类型
     * </pre>
     *
     * <code>.com.github.mxsm.serialization.protobuf.CtrlMessageType ctrlMessageType = 4;</code>
     * @param value The ctrlMessageType to set.
     * @return This builder for chaining.
     */
    public Builder setCtrlMessageType(com.github.mxsm.serialization.protobuf.CtrlMessageType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      ctrlMessageType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 控制消息类型
     * </pre>
     *
     * <code>.com.github.mxsm.serialization.protobuf.CtrlMessageType ctrlMessageType = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearCtrlMessageType() {
      
      ctrlMessageType_ = 0;
      onChanged();
      return this;
    }

    private boolean withCamera_ ;
    /**
     * <pre>
     * 拨号接听类型中是否使用视频聊天功能标志
     * </pre>
     *
     * <code>bool withCamera = 7;</code>
     * @return The withCamera.
     */
    @java.lang.Override
    public boolean getWithCamera() {
      return withCamera_;
    }
    /**
     * <pre>
     * 拨号接听类型中是否使用视频聊天功能标志
     * </pre>
     *
     * <code>bool withCamera = 7;</code>
     * @param value The withCamera to set.
     * @return This builder for chaining.
     */
    public Builder setWithCamera(boolean value) {
      
      withCamera_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 拨号接听类型中是否使用视频聊天功能标志
     * </pre>
     *
     * <code>bool withCamera = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearWithCamera() {
      
      withCamera_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.github.mxsm.serialization.protobuf.CtrlMessage)
  }

  // @@protoc_insertion_point(class_scope:com.github.mxsm.serialization.protobuf.CtrlMessage)
  private static final com.github.mxsm.serialization.protobuf.CtrlMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.github.mxsm.serialization.protobuf.CtrlMessage();
  }

  public static com.github.mxsm.serialization.protobuf.CtrlMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CtrlMessage>
      PARSER = new com.google.protobuf.AbstractParser<CtrlMessage>() {
    @java.lang.Override
    public CtrlMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CtrlMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CtrlMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CtrlMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.github.mxsm.serialization.protobuf.CtrlMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

