// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AntMessage.proto

package com.github.mxsm.serialization.protobuf;

public interface CtrlMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.github.mxsm.serialization.protobuf.CtrlMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 消息报文时间戳
   * </pre>
   *
   * <code>int64 messageTime = 1;</code>
   * @return The messageTime.
   */
  long getMessageTime();

  /**
   * <pre>
   * 消息报文ID，在同一次socket连接过程中保证唯一，即connId不变的情况下，该ID递增
   * </pre>
   *
   * <code>int32 messageId = 2;</code>
   * @return The messageId.
   */
  int getMessageId();

  /**
   * <pre>
   * 控制消息报文ID
   * </pre>
   *
   * <code>int64 ctrlMessageId = 3;</code>
   * @return The ctrlMessageId.
   */
  long getCtrlMessageId();

  /**
   * <pre>
   * 控制消息类型
   * </pre>
   *
   * <code>.com.github.mxsm.serialization.protobuf.CtrlMessageType ctrlMessageType = 4;</code>
   * @return The enum numeric value on the wire for ctrlMessageType.
   */
  int getCtrlMessageTypeValue();
  /**
   * <pre>
   * 控制消息类型
   * </pre>
   *
   * <code>.com.github.mxsm.serialization.protobuf.CtrlMessageType ctrlMessageType = 4;</code>
   * @return The ctrlMessageType.
   */
  com.github.mxsm.serialization.protobuf.CtrlMessageType getCtrlMessageType();

  /**
   * <pre>
   * 拨号接听类型中是否使用视频聊天功能标志
   * </pre>
   *
   * <code>bool withCamera = 7;</code>
   * @return The withCamera.
   */
  boolean getWithCamera();
}
