// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AntMessage.proto

package com.github.mxsm.serialization.protobuf;

public interface HeaderOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.github.mxsm.serialization.protobuf.Header)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 sender = 1;</code>
   * @return The sender.
   */
  long getSender();

  /**
   * <code>int64 receiver = 2;</code>
   * @return The receiver.
   */
  long getReceiver();

  /**
   * <code>.com.github.mxsm.serialization.protobuf.Terminal terminal = 3;</code>
   * @return Whether the terminal field is set.
   */
  boolean hasTerminal();
  /**
   * <code>.com.github.mxsm.serialization.protobuf.Terminal terminal = 3;</code>
   * @return The terminal.
   */
  com.github.mxsm.serialization.protobuf.Terminal getTerminal();
  /**
   * <code>.com.github.mxsm.serialization.protobuf.Terminal terminal = 3;</code>
   */
  com.github.mxsm.serialization.protobuf.TerminalOrBuilder getTerminalOrBuilder();

  /**
   * <code>.com.github.mxsm.serialization.protobuf.UserMetadata userMetadata = 4;</code>
   * @return Whether the userMetadata field is set.
   */
  boolean hasUserMetadata();
  /**
   * <code>.com.github.mxsm.serialization.protobuf.UserMetadata userMetadata = 4;</code>
   * @return The userMetadata.
   */
  com.github.mxsm.serialization.protobuf.UserMetadata getUserMetadata();
  /**
   * <code>.com.github.mxsm.serialization.protobuf.UserMetadata userMetadata = 4;</code>
   */
  com.github.mxsm.serialization.protobuf.UserMetadataOrBuilder getUserMetadataOrBuilder();
}
