// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AntMessage.proto

package com.github.mxsm.serialization.protobuf;

/**
 * <pre>
 * 内容信息消息体
 * </pre>
 *
 * Protobuf type {@code com.github.mxsm.serialization.protobuf.Message}
 */
public final class Message extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.github.mxsm.serialization.protobuf.Message)
    MessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Message.newBuilder() to construct.
  private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Message() {
    messageType_ = 0;
    messageContentType_ = 0;
    mediaLink_ = "";
    payload_ = com.google.protobuf.ByteString.EMPTY;
    originalLink_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Message();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Message(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            messageTime_ = input.readInt64();
            break;
          }
          case 16: {

            messageId_ = input.readInt64();
            break;
          }
          case 24: {
            int rawValue = input.readEnum();

            messageType_ = rawValue;
            break;
          }
          case 32: {
            int rawValue = input.readEnum();

            messageContentType_ = rawValue;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            mediaLink_ = s;
            break;
          }
          case 50: {

            payload_ = input.readBytes();
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            originalLink_ = s;
            break;
          }
          case 64: {

            quotationMessageId_ = input.readInt32();
            break;
          }
          case 72: {

            isAsync_ = input.readBool();
            break;
          }
          case 80: {

            isBurn_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.github.mxsm.serialization.protobuf.AntMessage.internal_static_com_github_mxsm_serialization_protobuf_Message_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.github.mxsm.serialization.protobuf.AntMessage.internal_static_com_github_mxsm_serialization_protobuf_Message_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.github.mxsm.serialization.protobuf.Message.class, com.github.mxsm.serialization.protobuf.Message.Builder.class);
  }

  public static final int MESSAGETIME_FIELD_NUMBER = 1;
  private long messageTime_;
  /**
   * <pre>
   * 消息报文时间戳
   * </pre>
   *
   * <code>int64 messageTime = 1;</code>
   * @return The messageTime.
   */
  @java.lang.Override
  public long getMessageTime() {
    return messageTime_;
  }

  public static final int MESSAGEID_FIELD_NUMBER = 2;
  private long messageId_;
  /**
   * <pre>
   * 消息报文ID，在同一次socket连接过程中保证唯一，即connId不变的情况下，该ID递增
   * </pre>
   *
   * <code>int64 messageId = 2;</code>
   * @return The messageId.
   */
  @java.lang.Override
  public long getMessageId() {
    return messageId_;
  }

  public static final int MESSAGETYPE_FIELD_NUMBER = 3;
  private int messageType_;
  /**
   * <pre>
   * 业务类型，如p2p, group, card, red等
   * </pre>
   *
   * <code>.com.github.mxsm.serialization.protobuf.MessageType messageType = 3;</code>
   * @return The enum numeric value on the wire for messageType.
   */
  @java.lang.Override public int getMessageTypeValue() {
    return messageType_;
  }
  /**
   * <pre>
   * 业务类型，如p2p, group, card, red等
   * </pre>
   *
   * <code>.com.github.mxsm.serialization.protobuf.MessageType messageType = 3;</code>
   * @return The messageType.
   */
  @java.lang.Override public com.github.mxsm.serialization.protobuf.MessageType getMessageType() {
    @SuppressWarnings("deprecation")
    com.github.mxsm.serialization.protobuf.MessageType result = com.github.mxsm.serialization.protobuf.MessageType.valueOf(messageType_);
    return result == null ? com.github.mxsm.serialization.protobuf.MessageType.UNRECOGNIZED : result;
  }

  public static final int MESSAGECONTENTTYPE_FIELD_NUMBER = 4;
  private int messageContentType_;
  /**
   * <pre>
   * 内容消息类型
   * </pre>
   *
   * <code>.com.github.mxsm.serialization.protobuf.MessageContentType messageContentType = 4;</code>
   * @return The enum numeric value on the wire for messageContentType.
   */
  @java.lang.Override public int getMessageContentTypeValue() {
    return messageContentType_;
  }
  /**
   * <pre>
   * 内容消息类型
   * </pre>
   *
   * <code>.com.github.mxsm.serialization.protobuf.MessageContentType messageContentType = 4;</code>
   * @return The messageContentType.
   */
  @java.lang.Override public com.github.mxsm.serialization.protobuf.MessageContentType getMessageContentType() {
    @SuppressWarnings("deprecation")
    com.github.mxsm.serialization.protobuf.MessageContentType result = com.github.mxsm.serialization.protobuf.MessageContentType.valueOf(messageContentType_);
    return result == null ? com.github.mxsm.serialization.protobuf.MessageContentType.UNRECOGNIZED : result;
  }

  public static final int MEDIALINK_FIELD_NUMBER = 5;
  private volatile java.lang.Object mediaLink_;
  /**
   * <pre>
   * 内容消息额外链接URL地址
   * </pre>
   *
   * <code>string mediaLink = 5;</code>
   * @return The mediaLink.
   */
  @java.lang.Override
  public java.lang.String getMediaLink() {
    java.lang.Object ref = mediaLink_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      mediaLink_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 内容消息额外链接URL地址
   * </pre>
   *
   * <code>string mediaLink = 5;</code>
   * @return The bytes for mediaLink.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMediaLinkBytes() {
    java.lang.Object ref = mediaLink_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      mediaLink_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PAYLOAD_FIELD_NUMBER = 6;
  private com.google.protobuf.ByteString payload_;
  /**
   * <pre>
   * 消息负载
   * </pre>
   *
   * <code>bytes payload = 6;</code>
   * @return The payload.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getPayload() {
    return payload_;
  }

  public static final int ORIGINALLINK_FIELD_NUMBER = 7;
  private volatile java.lang.Object originalLink_;
  /**
   * <pre>
   * 原图链接URL地址，预留
   * </pre>
   *
   * <code>string originalLink = 7;</code>
   * @return The originalLink.
   */
  @java.lang.Override
  public java.lang.String getOriginalLink() {
    java.lang.Object ref = originalLink_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      originalLink_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 原图链接URL地址，预留
   * </pre>
   *
   * <code>string originalLink = 7;</code>
   * @return The bytes for originalLink.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOriginalLinkBytes() {
    java.lang.Object ref = originalLink_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      originalLink_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int QUOTATIONMESSAGEID_FIELD_NUMBER = 8;
  private int quotationMessageId_;
  /**
   * <pre>
   * 回复引用的消息报文ID，该引用的消息报文必须在本消息包中存在，预留
   * </pre>
   *
   * <code>int32 quotationMessageId = 8;</code>
   * @return The quotationMessageId.
   */
  @java.lang.Override
  public int getQuotationMessageId() {
    return quotationMessageId_;
  }

  public static final int ISASYNC_FIELD_NUMBER = 9;
  private boolean isAsync_;
  /**
   * <pre>
   * 是否需要回复ack的标志
   * </pre>
   *
   * <code>bool isAsync = 9;</code>
   * @return The isAsync.
   */
  @java.lang.Override
  public boolean getIsAsync() {
    return isAsync_;
  }

  public static final int ISBURN_FIELD_NUMBER = 10;
  private boolean isBurn_;
  /**
   * <pre>
   * 是否为阅后即焚消息标志，预留
   * </pre>
   *
   * <code>bool isBurn = 10;</code>
   * @return The isBurn.
   */
  @java.lang.Override
  public boolean getIsBurn() {
    return isBurn_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (messageTime_ != 0L) {
      output.writeInt64(1, messageTime_);
    }
    if (messageId_ != 0L) {
      output.writeInt64(2, messageId_);
    }
    if (messageType_ != com.github.mxsm.serialization.protobuf.MessageType.P2P.getNumber()) {
      output.writeEnum(3, messageType_);
    }
    if (messageContentType_ != com.github.mxsm.serialization.protobuf.MessageContentType.PLAINTEXT.getNumber()) {
      output.writeEnum(4, messageContentType_);
    }
    if (!getMediaLinkBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, mediaLink_);
    }
    if (!payload_.isEmpty()) {
      output.writeBytes(6, payload_);
    }
    if (!getOriginalLinkBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, originalLink_);
    }
    if (quotationMessageId_ != 0) {
      output.writeInt32(8, quotationMessageId_);
    }
    if (isAsync_ != false) {
      output.writeBool(9, isAsync_);
    }
    if (isBurn_ != false) {
      output.writeBool(10, isBurn_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (messageTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, messageTime_);
    }
    if (messageId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, messageId_);
    }
    if (messageType_ != com.github.mxsm.serialization.protobuf.MessageType.P2P.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, messageType_);
    }
    if (messageContentType_ != com.github.mxsm.serialization.protobuf.MessageContentType.PLAINTEXT.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, messageContentType_);
    }
    if (!getMediaLinkBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, mediaLink_);
    }
    if (!payload_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(6, payload_);
    }
    if (!getOriginalLinkBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, originalLink_);
    }
    if (quotationMessageId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(8, quotationMessageId_);
    }
    if (isAsync_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(9, isAsync_);
    }
    if (isBurn_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(10, isBurn_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.github.mxsm.serialization.protobuf.Message)) {
      return super.equals(obj);
    }
    com.github.mxsm.serialization.protobuf.Message other = (com.github.mxsm.serialization.protobuf.Message) obj;

    if (getMessageTime()
        != other.getMessageTime()) return false;
    if (getMessageId()
        != other.getMessageId()) return false;
    if (messageType_ != other.messageType_) return false;
    if (messageContentType_ != other.messageContentType_) return false;
    if (!getMediaLink()
        .equals(other.getMediaLink())) return false;
    if (!getPayload()
        .equals(other.getPayload())) return false;
    if (!getOriginalLink()
        .equals(other.getOriginalLink())) return false;
    if (getQuotationMessageId()
        != other.getQuotationMessageId()) return false;
    if (getIsAsync()
        != other.getIsAsync()) return false;
    if (getIsBurn()
        != other.getIsBurn()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MESSAGETIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getMessageTime());
    hash = (37 * hash) + MESSAGEID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getMessageId());
    hash = (37 * hash) + MESSAGETYPE_FIELD_NUMBER;
    hash = (53 * hash) + messageType_;
    hash = (37 * hash) + MESSAGECONTENTTYPE_FIELD_NUMBER;
    hash = (53 * hash) + messageContentType_;
    hash = (37 * hash) + MEDIALINK_FIELD_NUMBER;
    hash = (53 * hash) + getMediaLink().hashCode();
    hash = (37 * hash) + PAYLOAD_FIELD_NUMBER;
    hash = (53 * hash) + getPayload().hashCode();
    hash = (37 * hash) + ORIGINALLINK_FIELD_NUMBER;
    hash = (53 * hash) + getOriginalLink().hashCode();
    hash = (37 * hash) + QUOTATIONMESSAGEID_FIELD_NUMBER;
    hash = (53 * hash) + getQuotationMessageId();
    hash = (37 * hash) + ISASYNC_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsAsync());
    hash = (37 * hash) + ISBURN_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsBurn());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.github.mxsm.serialization.protobuf.Message parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.mxsm.serialization.protobuf.Message parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.mxsm.serialization.protobuf.Message parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.mxsm.serialization.protobuf.Message parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.mxsm.serialization.protobuf.Message parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.mxsm.serialization.protobuf.Message parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.mxsm.serialization.protobuf.Message parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.mxsm.serialization.protobuf.Message parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.mxsm.serialization.protobuf.Message parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.github.mxsm.serialization.protobuf.Message parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.mxsm.serialization.protobuf.Message parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.mxsm.serialization.protobuf.Message parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.github.mxsm.serialization.protobuf.Message prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 内容信息消息体
   * </pre>
   *
   * Protobuf type {@code com.github.mxsm.serialization.protobuf.Message}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.github.mxsm.serialization.protobuf.Message)
      com.github.mxsm.serialization.protobuf.MessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.mxsm.serialization.protobuf.AntMessage.internal_static_com_github_mxsm_serialization_protobuf_Message_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.mxsm.serialization.protobuf.AntMessage.internal_static_com_github_mxsm_serialization_protobuf_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.mxsm.serialization.protobuf.Message.class, com.github.mxsm.serialization.protobuf.Message.Builder.class);
    }

    // Construct using com.github.mxsm.serialization.protobuf.Message.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      messageTime_ = 0L;

      messageId_ = 0L;

      messageType_ = 0;

      messageContentType_ = 0;

      mediaLink_ = "";

      payload_ = com.google.protobuf.ByteString.EMPTY;

      originalLink_ = "";

      quotationMessageId_ = 0;

      isAsync_ = false;

      isBurn_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.github.mxsm.serialization.protobuf.AntMessage.internal_static_com_github_mxsm_serialization_protobuf_Message_descriptor;
    }

    @java.lang.Override
    public com.github.mxsm.serialization.protobuf.Message getDefaultInstanceForType() {
      return com.github.mxsm.serialization.protobuf.Message.getDefaultInstance();
    }

    @java.lang.Override
    public com.github.mxsm.serialization.protobuf.Message build() {
      com.github.mxsm.serialization.protobuf.Message result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.github.mxsm.serialization.protobuf.Message buildPartial() {
      com.github.mxsm.serialization.protobuf.Message result = new com.github.mxsm.serialization.protobuf.Message(this);
      result.messageTime_ = messageTime_;
      result.messageId_ = messageId_;
      result.messageType_ = messageType_;
      result.messageContentType_ = messageContentType_;
      result.mediaLink_ = mediaLink_;
      result.payload_ = payload_;
      result.originalLink_ = originalLink_;
      result.quotationMessageId_ = quotationMessageId_;
      result.isAsync_ = isAsync_;
      result.isBurn_ = isBurn_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.github.mxsm.serialization.protobuf.Message) {
        return mergeFrom((com.github.mxsm.serialization.protobuf.Message)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.github.mxsm.serialization.protobuf.Message other) {
      if (other == com.github.mxsm.serialization.protobuf.Message.getDefaultInstance()) return this;
      if (other.getMessageTime() != 0L) {
        setMessageTime(other.getMessageTime());
      }
      if (other.getMessageId() != 0L) {
        setMessageId(other.getMessageId());
      }
      if (other.messageType_ != 0) {
        setMessageTypeValue(other.getMessageTypeValue());
      }
      if (other.messageContentType_ != 0) {
        setMessageContentTypeValue(other.getMessageContentTypeValue());
      }
      if (!other.getMediaLink().isEmpty()) {
        mediaLink_ = other.mediaLink_;
        onChanged();
      }
      if (other.getPayload() != com.google.protobuf.ByteString.EMPTY) {
        setPayload(other.getPayload());
      }
      if (!other.getOriginalLink().isEmpty()) {
        originalLink_ = other.originalLink_;
        onChanged();
      }
      if (other.getQuotationMessageId() != 0) {
        setQuotationMessageId(other.getQuotationMessageId());
      }
      if (other.getIsAsync() != false) {
        setIsAsync(other.getIsAsync());
      }
      if (other.getIsBurn() != false) {
        setIsBurn(other.getIsBurn());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.github.mxsm.serialization.protobuf.Message parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.github.mxsm.serialization.protobuf.Message) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long messageTime_ ;
    /**
     * <pre>
     * 消息报文时间戳
     * </pre>
     *
     * <code>int64 messageTime = 1;</code>
     * @return The messageTime.
     */
    @java.lang.Override
    public long getMessageTime() {
      return messageTime_;
    }
    /**
     * <pre>
     * 消息报文时间戳
     * </pre>
     *
     * <code>int64 messageTime = 1;</code>
     * @param value The messageTime to set.
     * @return This builder for chaining.
     */
    public Builder setMessageTime(long value) {
      
      messageTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 消息报文时间戳
     * </pre>
     *
     * <code>int64 messageTime = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMessageTime() {
      
      messageTime_ = 0L;
      onChanged();
      return this;
    }

    private long messageId_ ;
    /**
     * <pre>
     * 消息报文ID，在同一次socket连接过程中保证唯一，即connId不变的情况下，该ID递增
     * </pre>
     *
     * <code>int64 messageId = 2;</code>
     * @return The messageId.
     */
    @java.lang.Override
    public long getMessageId() {
      return messageId_;
    }
    /**
     * <pre>
     * 消息报文ID，在同一次socket连接过程中保证唯一，即connId不变的情况下，该ID递增
     * </pre>
     *
     * <code>int64 messageId = 2;</code>
     * @param value The messageId to set.
     * @return This builder for chaining.
     */
    public Builder setMessageId(long value) {
      
      messageId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 消息报文ID，在同一次socket连接过程中保证唯一，即connId不变的情况下，该ID递增
     * </pre>
     *
     * <code>int64 messageId = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearMessageId() {
      
      messageId_ = 0L;
      onChanged();
      return this;
    }

    private int messageType_ = 0;
    /**
     * <pre>
     * 业务类型，如p2p, group, card, red等
     * </pre>
     *
     * <code>.com.github.mxsm.serialization.protobuf.MessageType messageType = 3;</code>
     * @return The enum numeric value on the wire for messageType.
     */
    @java.lang.Override public int getMessageTypeValue() {
      return messageType_;
    }
    /**
     * <pre>
     * 业务类型，如p2p, group, card, red等
     * </pre>
     *
     * <code>.com.github.mxsm.serialization.protobuf.MessageType messageType = 3;</code>
     * @param value The enum numeric value on the wire for messageType to set.
     * @return This builder for chaining.
     */
    public Builder setMessageTypeValue(int value) {
      
      messageType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 业务类型，如p2p, group, card, red等
     * </pre>
     *
     * <code>.com.github.mxsm.serialization.protobuf.MessageType messageType = 3;</code>
     * @return The messageType.
     */
    @java.lang.Override
    public com.github.mxsm.serialization.protobuf.MessageType getMessageType() {
      @SuppressWarnings("deprecation")
      com.github.mxsm.serialization.protobuf.MessageType result = com.github.mxsm.serialization.protobuf.MessageType.valueOf(messageType_);
      return result == null ? com.github.mxsm.serialization.protobuf.MessageType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * 业务类型，如p2p, group, card, red等
     * </pre>
     *
     * <code>.com.github.mxsm.serialization.protobuf.MessageType messageType = 3;</code>
     * @param value The messageType to set.
     * @return This builder for chaining.
     */
    public Builder setMessageType(com.github.mxsm.serialization.protobuf.MessageType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      messageType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 业务类型，如p2p, group, card, red等
     * </pre>
     *
     * <code>.com.github.mxsm.serialization.protobuf.MessageType messageType = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearMessageType() {
      
      messageType_ = 0;
      onChanged();
      return this;
    }

    private int messageContentType_ = 0;
    /**
     * <pre>
     * 内容消息类型
     * </pre>
     *
     * <code>.com.github.mxsm.serialization.protobuf.MessageContentType messageContentType = 4;</code>
     * @return The enum numeric value on the wire for messageContentType.
     */
    @java.lang.Override public int getMessageContentTypeValue() {
      return messageContentType_;
    }
    /**
     * <pre>
     * 内容消息类型
     * </pre>
     *
     * <code>.com.github.mxsm.serialization.protobuf.MessageContentType messageContentType = 4;</code>
     * @param value The enum numeric value on the wire for messageContentType to set.
     * @return This builder for chaining.
     */
    public Builder setMessageContentTypeValue(int value) {
      
      messageContentType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 内容消息类型
     * </pre>
     *
     * <code>.com.github.mxsm.serialization.protobuf.MessageContentType messageContentType = 4;</code>
     * @return The messageContentType.
     */
    @java.lang.Override
    public com.github.mxsm.serialization.protobuf.MessageContentType getMessageContentType() {
      @SuppressWarnings("deprecation")
      com.github.mxsm.serialization.protobuf.MessageContentType result = com.github.mxsm.serialization.protobuf.MessageContentType.valueOf(messageContentType_);
      return result == null ? com.github.mxsm.serialization.protobuf.MessageContentType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * 内容消息类型
     * </pre>
     *
     * <code>.com.github.mxsm.serialization.protobuf.MessageContentType messageContentType = 4;</code>
     * @param value The messageContentType to set.
     * @return This builder for chaining.
     */
    public Builder setMessageContentType(com.github.mxsm.serialization.protobuf.MessageContentType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      messageContentType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 内容消息类型
     * </pre>
     *
     * <code>.com.github.mxsm.serialization.protobuf.MessageContentType messageContentType = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearMessageContentType() {
      
      messageContentType_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object mediaLink_ = "";
    /**
     * <pre>
     * 内容消息额外链接URL地址
     * </pre>
     *
     * <code>string mediaLink = 5;</code>
     * @return The mediaLink.
     */
    public java.lang.String getMediaLink() {
      java.lang.Object ref = mediaLink_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mediaLink_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 内容消息额外链接URL地址
     * </pre>
     *
     * <code>string mediaLink = 5;</code>
     * @return The bytes for mediaLink.
     */
    public com.google.protobuf.ByteString
        getMediaLinkBytes() {
      java.lang.Object ref = mediaLink_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mediaLink_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 内容消息额外链接URL地址
     * </pre>
     *
     * <code>string mediaLink = 5;</code>
     * @param value The mediaLink to set.
     * @return This builder for chaining.
     */
    public Builder setMediaLink(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      mediaLink_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 内容消息额外链接URL地址
     * </pre>
     *
     * <code>string mediaLink = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearMediaLink() {
      
      mediaLink_ = getDefaultInstance().getMediaLink();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 内容消息额外链接URL地址
     * </pre>
     *
     * <code>string mediaLink = 5;</code>
     * @param value The bytes for mediaLink to set.
     * @return This builder for chaining.
     */
    public Builder setMediaLinkBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      mediaLink_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * 消息负载
     * </pre>
     *
     * <code>bytes payload = 6;</code>
     * @return The payload.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getPayload() {
      return payload_;
    }
    /**
     * <pre>
     * 消息负载
     * </pre>
     *
     * <code>bytes payload = 6;</code>
     * @param value The payload to set.
     * @return This builder for chaining.
     */
    public Builder setPayload(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      payload_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 消息负载
     * </pre>
     *
     * <code>bytes payload = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearPayload() {
      
      payload_ = getDefaultInstance().getPayload();
      onChanged();
      return this;
    }

    private java.lang.Object originalLink_ = "";
    /**
     * <pre>
     * 原图链接URL地址，预留
     * </pre>
     *
     * <code>string originalLink = 7;</code>
     * @return The originalLink.
     */
    public java.lang.String getOriginalLink() {
      java.lang.Object ref = originalLink_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        originalLink_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 原图链接URL地址，预留
     * </pre>
     *
     * <code>string originalLink = 7;</code>
     * @return The bytes for originalLink.
     */
    public com.google.protobuf.ByteString
        getOriginalLinkBytes() {
      java.lang.Object ref = originalLink_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        originalLink_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 原图链接URL地址，预留
     * </pre>
     *
     * <code>string originalLink = 7;</code>
     * @param value The originalLink to set.
     * @return This builder for chaining.
     */
    public Builder setOriginalLink(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      originalLink_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 原图链接URL地址，预留
     * </pre>
     *
     * <code>string originalLink = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearOriginalLink() {
      
      originalLink_ = getDefaultInstance().getOriginalLink();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 原图链接URL地址，预留
     * </pre>
     *
     * <code>string originalLink = 7;</code>
     * @param value The bytes for originalLink to set.
     * @return This builder for chaining.
     */
    public Builder setOriginalLinkBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      originalLink_ = value;
      onChanged();
      return this;
    }

    private int quotationMessageId_ ;
    /**
     * <pre>
     * 回复引用的消息报文ID，该引用的消息报文必须在本消息包中存在，预留
     * </pre>
     *
     * <code>int32 quotationMessageId = 8;</code>
     * @return The quotationMessageId.
     */
    @java.lang.Override
    public int getQuotationMessageId() {
      return quotationMessageId_;
    }
    /**
     * <pre>
     * 回复引用的消息报文ID，该引用的消息报文必须在本消息包中存在，预留
     * </pre>
     *
     * <code>int32 quotationMessageId = 8;</code>
     * @param value The quotationMessageId to set.
     * @return This builder for chaining.
     */
    public Builder setQuotationMessageId(int value) {
      
      quotationMessageId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 回复引用的消息报文ID，该引用的消息报文必须在本消息包中存在，预留
     * </pre>
     *
     * <code>int32 quotationMessageId = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearQuotationMessageId() {
      
      quotationMessageId_ = 0;
      onChanged();
      return this;
    }

    private boolean isAsync_ ;
    /**
     * <pre>
     * 是否需要回复ack的标志
     * </pre>
     *
     * <code>bool isAsync = 9;</code>
     * @return The isAsync.
     */
    @java.lang.Override
    public boolean getIsAsync() {
      return isAsync_;
    }
    /**
     * <pre>
     * 是否需要回复ack的标志
     * </pre>
     *
     * <code>bool isAsync = 9;</code>
     * @param value The isAsync to set.
     * @return This builder for chaining.
     */
    public Builder setIsAsync(boolean value) {
      
      isAsync_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 是否需要回复ack的标志
     * </pre>
     *
     * <code>bool isAsync = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsAsync() {
      
      isAsync_ = false;
      onChanged();
      return this;
    }

    private boolean isBurn_ ;
    /**
     * <pre>
     * 是否为阅后即焚消息标志，预留
     * </pre>
     *
     * <code>bool isBurn = 10;</code>
     * @return The isBurn.
     */
    @java.lang.Override
    public boolean getIsBurn() {
      return isBurn_;
    }
    /**
     * <pre>
     * 是否为阅后即焚消息标志，预留
     * </pre>
     *
     * <code>bool isBurn = 10;</code>
     * @param value The isBurn to set.
     * @return This builder for chaining.
     */
    public Builder setIsBurn(boolean value) {
      
      isBurn_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 是否为阅后即焚消息标志，预留
     * </pre>
     *
     * <code>bool isBurn = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsBurn() {
      
      isBurn_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.github.mxsm.serialization.protobuf.Message)
  }

  // @@protoc_insertion_point(class_scope:com.github.mxsm.serialization.protobuf.Message)
  private static final com.github.mxsm.serialization.protobuf.Message DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.github.mxsm.serialization.protobuf.Message();
  }

  public static com.github.mxsm.serialization.protobuf.Message getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Message>
      PARSER = new com.google.protobuf.AbstractParser<Message>() {
    @java.lang.Override
    public Message parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Message(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Message> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Message> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.github.mxsm.serialization.protobuf.Message getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

