// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AntMessage.proto

package com.github.mxsm.serialization.protobuf;

/**
 * Protobuf enum {@code com.github.mxsm.serialization.protobuf.MessageContentType}
 */
public enum MessageContentType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   * 纯文本
   * </pre>
   *
   * <code>PLAINTEXT = 0;</code>
   */
  PLAINTEXT(0),
  /**
   * <pre>
   * HTML文本
   * </pre>
   *
   * <code>HTML = 1;</code>
   */
  HTML(1),
  /**
   * <pre>
   * JSON对象
   * </pre>
   *
   * <code>JSON = 2;</code>
   */
  JSON(2),
  /**
   * <pre>
   * YAML配置
   * </pre>
   *
   * <code>YAML = 3;</code>
   */
  YAML(3),
  /**
   * <pre>
   * 图像
   * </pre>
   *
   * <code>IMAGE = 4;</code>
   */
  IMAGE(4),
  /**
   * <pre>
   * 声音
   * </pre>
   *
   * <code>AUDIO = 5;</code>
   */
  AUDIO(5),
  /**
   * <pre>
   * 视频
   * </pre>
   *
   * <code>VIDEO = 6;</code>
   */
  VIDEO(6),
  UNRECOGNIZED(-1),
  ;

  /**
   * <pre>
   * 纯文本
   * </pre>
   *
   * <code>PLAINTEXT = 0;</code>
   */
  public static final int PLAINTEXT_VALUE = 0;
  /**
   * <pre>
   * HTML文本
   * </pre>
   *
   * <code>HTML = 1;</code>
   */
  public static final int HTML_VALUE = 1;
  /**
   * <pre>
   * JSON对象
   * </pre>
   *
   * <code>JSON = 2;</code>
   */
  public static final int JSON_VALUE = 2;
  /**
   * <pre>
   * YAML配置
   * </pre>
   *
   * <code>YAML = 3;</code>
   */
  public static final int YAML_VALUE = 3;
  /**
   * <pre>
   * 图像
   * </pre>
   *
   * <code>IMAGE = 4;</code>
   */
  public static final int IMAGE_VALUE = 4;
  /**
   * <pre>
   * 声音
   * </pre>
   *
   * <code>AUDIO = 5;</code>
   */
  public static final int AUDIO_VALUE = 5;
  /**
   * <pre>
   * 视频
   * </pre>
   *
   * <code>VIDEO = 6;</code>
   */
  public static final int VIDEO_VALUE = 6;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static MessageContentType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static MessageContentType forNumber(int value) {
    switch (value) {
      case 0: return PLAINTEXT;
      case 1: return HTML;
      case 2: return JSON;
      case 3: return YAML;
      case 4: return IMAGE;
      case 5: return AUDIO;
      case 6: return VIDEO;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<MessageContentType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      MessageContentType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<MessageContentType>() {
          public MessageContentType findValueByNumber(int number) {
            return MessageContentType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.github.mxsm.serialization.protobuf.AntMessage.getDescriptor().getEnumTypes().get(3);
  }

  private static final MessageContentType[] VALUES = values();

  public static MessageContentType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private MessageContentType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:com.github.mxsm.serialization.protobuf.MessageContentType)
}

