// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AntMessage.proto

package com.github.mxsm.serialization.protobuf;

/**
 * <pre>
 * 终端信息消息体
 * </pre>
 *
 * Protobuf type {@code com.github.mxsm.serialization.protobuf.Terminal}
 */
public final class Terminal extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.github.mxsm.serialization.protobuf.Terminal)
    TerminalOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Terminal.newBuilder() to construct.
  private Terminal(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Terminal() {
    termType_ = 0;
    deviceType_ = "";
    osType_ = "";
    deviceToken_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Terminal();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Terminal(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            termType_ = rawValue;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            deviceType_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            osType_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            deviceToken_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.github.mxsm.serialization.protobuf.AntMessage.internal_static_com_github_mxsm_serialization_protobuf_Terminal_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.github.mxsm.serialization.protobuf.AntMessage.internal_static_com_github_mxsm_serialization_protobuf_Terminal_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.github.mxsm.serialization.protobuf.Terminal.class, com.github.mxsm.serialization.protobuf.Terminal.Builder.class);
  }

  public static final int TERMTYPE_FIELD_NUMBER = 1;
  private int termType_;
  /**
   * <pre>
   * 终端类型，可能取值：Android, ios, web, DesktopApp, TestClient
   * </pre>
   *
   * <code>.com.github.mxsm.serialization.protobuf.TerminalType termType = 1;</code>
   * @return The enum numeric value on the wire for termType.
   */
  @java.lang.Override public int getTermTypeValue() {
    return termType_;
  }
  /**
   * <pre>
   * 终端类型，可能取值：Android, ios, web, DesktopApp, TestClient
   * </pre>
   *
   * <code>.com.github.mxsm.serialization.protobuf.TerminalType termType = 1;</code>
   * @return The termType.
   */
  @java.lang.Override public com.github.mxsm.serialization.protobuf.TerminalType getTermType() {
    @SuppressWarnings("deprecation")
    com.github.mxsm.serialization.protobuf.TerminalType result = com.github.mxsm.serialization.protobuf.TerminalType.valueOf(termType_);
    return result == null ? com.github.mxsm.serialization.protobuf.TerminalType.UNRECOGNIZED : result;
  }

  public static final int DEVICETYPE_FIELD_NUMBER = 2;
  private volatile java.lang.Object deviceType_;
  /**
   * <pre>
   * 设备型号，如华为P10, iPhoneX, iPad3, Chrome等
   * </pre>
   *
   * <code>string deviceType = 2;</code>
   * @return The deviceType.
   */
  @java.lang.Override
  public java.lang.String getDeviceType() {
    java.lang.Object ref = deviceType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      deviceType_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 设备型号，如华为P10, iPhoneX, iPad3, Chrome等
   * </pre>
   *
   * <code>string deviceType = 2;</code>
   * @return The bytes for deviceType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDeviceTypeBytes() {
    java.lang.Object ref = deviceType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      deviceType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OSTYPE_FIELD_NUMBER = 3;
  private volatile java.lang.Object osType_;
  /**
   * <pre>
   * 操作系统型号，如Android7.2, iOS11, Windows10等
   * </pre>
   *
   * <code>string osType = 3;</code>
   * @return The osType.
   */
  @java.lang.Override
  public java.lang.String getOsType() {
    java.lang.Object ref = osType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      osType_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 操作系统型号，如Android7.2, iOS11, Windows10等
   * </pre>
   *
   * <code>string osType = 3;</code>
   * @return The bytes for osType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOsTypeBytes() {
    java.lang.Object ref = osType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      osType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DEVICETOKEN_FIELD_NUMBER = 4;
  private volatile java.lang.Object deviceToken_;
  /**
   * <pre>
   * 设备编码
   * </pre>
   *
   * <code>string deviceToken = 4;</code>
   * @return The deviceToken.
   */
  @java.lang.Override
  public java.lang.String getDeviceToken() {
    java.lang.Object ref = deviceToken_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      deviceToken_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 设备编码
   * </pre>
   *
   * <code>string deviceToken = 4;</code>
   * @return The bytes for deviceToken.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDeviceTokenBytes() {
    java.lang.Object ref = deviceToken_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      deviceToken_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (termType_ != com.github.mxsm.serialization.protobuf.TerminalType.ANDROID.getNumber()) {
      output.writeEnum(1, termType_);
    }
    if (!getDeviceTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, deviceType_);
    }
    if (!getOsTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, osType_);
    }
    if (!getDeviceTokenBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, deviceToken_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (termType_ != com.github.mxsm.serialization.protobuf.TerminalType.ANDROID.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, termType_);
    }
    if (!getDeviceTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, deviceType_);
    }
    if (!getOsTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, osType_);
    }
    if (!getDeviceTokenBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, deviceToken_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.github.mxsm.serialization.protobuf.Terminal)) {
      return super.equals(obj);
    }
    com.github.mxsm.serialization.protobuf.Terminal other = (com.github.mxsm.serialization.protobuf.Terminal) obj;

    if (termType_ != other.termType_) return false;
    if (!getDeviceType()
        .equals(other.getDeviceType())) return false;
    if (!getOsType()
        .equals(other.getOsType())) return false;
    if (!getDeviceToken()
        .equals(other.getDeviceToken())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TERMTYPE_FIELD_NUMBER;
    hash = (53 * hash) + termType_;
    hash = (37 * hash) + DEVICETYPE_FIELD_NUMBER;
    hash = (53 * hash) + getDeviceType().hashCode();
    hash = (37 * hash) + OSTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getOsType().hashCode();
    hash = (37 * hash) + DEVICETOKEN_FIELD_NUMBER;
    hash = (53 * hash) + getDeviceToken().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.github.mxsm.serialization.protobuf.Terminal parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.mxsm.serialization.protobuf.Terminal parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.mxsm.serialization.protobuf.Terminal parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.mxsm.serialization.protobuf.Terminal parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.mxsm.serialization.protobuf.Terminal parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.mxsm.serialization.protobuf.Terminal parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.mxsm.serialization.protobuf.Terminal parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.mxsm.serialization.protobuf.Terminal parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.mxsm.serialization.protobuf.Terminal parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.github.mxsm.serialization.protobuf.Terminal parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.mxsm.serialization.protobuf.Terminal parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.mxsm.serialization.protobuf.Terminal parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.github.mxsm.serialization.protobuf.Terminal prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 终端信息消息体
   * </pre>
   *
   * Protobuf type {@code com.github.mxsm.serialization.protobuf.Terminal}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.github.mxsm.serialization.protobuf.Terminal)
      com.github.mxsm.serialization.protobuf.TerminalOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.mxsm.serialization.protobuf.AntMessage.internal_static_com_github_mxsm_serialization_protobuf_Terminal_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.mxsm.serialization.protobuf.AntMessage.internal_static_com_github_mxsm_serialization_protobuf_Terminal_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.mxsm.serialization.protobuf.Terminal.class, com.github.mxsm.serialization.protobuf.Terminal.Builder.class);
    }

    // Construct using com.github.mxsm.serialization.protobuf.Terminal.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      termType_ = 0;

      deviceType_ = "";

      osType_ = "";

      deviceToken_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.github.mxsm.serialization.protobuf.AntMessage.internal_static_com_github_mxsm_serialization_protobuf_Terminal_descriptor;
    }

    @java.lang.Override
    public com.github.mxsm.serialization.protobuf.Terminal getDefaultInstanceForType() {
      return com.github.mxsm.serialization.protobuf.Terminal.getDefaultInstance();
    }

    @java.lang.Override
    public com.github.mxsm.serialization.protobuf.Terminal build() {
      com.github.mxsm.serialization.protobuf.Terminal result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.github.mxsm.serialization.protobuf.Terminal buildPartial() {
      com.github.mxsm.serialization.protobuf.Terminal result = new com.github.mxsm.serialization.protobuf.Terminal(this);
      result.termType_ = termType_;
      result.deviceType_ = deviceType_;
      result.osType_ = osType_;
      result.deviceToken_ = deviceToken_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.github.mxsm.serialization.protobuf.Terminal) {
        return mergeFrom((com.github.mxsm.serialization.protobuf.Terminal)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.github.mxsm.serialization.protobuf.Terminal other) {
      if (other == com.github.mxsm.serialization.protobuf.Terminal.getDefaultInstance()) return this;
      if (other.termType_ != 0) {
        setTermTypeValue(other.getTermTypeValue());
      }
      if (!other.getDeviceType().isEmpty()) {
        deviceType_ = other.deviceType_;
        onChanged();
      }
      if (!other.getOsType().isEmpty()) {
        osType_ = other.osType_;
        onChanged();
      }
      if (!other.getDeviceToken().isEmpty()) {
        deviceToken_ = other.deviceToken_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.github.mxsm.serialization.protobuf.Terminal parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.github.mxsm.serialization.protobuf.Terminal) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int termType_ = 0;
    /**
     * <pre>
     * 终端类型，可能取值：Android, ios, web, DesktopApp, TestClient
     * </pre>
     *
     * <code>.com.github.mxsm.serialization.protobuf.TerminalType termType = 1;</code>
     * @return The enum numeric value on the wire for termType.
     */
    @java.lang.Override public int getTermTypeValue() {
      return termType_;
    }
    /**
     * <pre>
     * 终端类型，可能取值：Android, ios, web, DesktopApp, TestClient
     * </pre>
     *
     * <code>.com.github.mxsm.serialization.protobuf.TerminalType termType = 1;</code>
     * @param value The enum numeric value on the wire for termType to set.
     * @return This builder for chaining.
     */
    public Builder setTermTypeValue(int value) {
      
      termType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 终端类型，可能取值：Android, ios, web, DesktopApp, TestClient
     * </pre>
     *
     * <code>.com.github.mxsm.serialization.protobuf.TerminalType termType = 1;</code>
     * @return The termType.
     */
    @java.lang.Override
    public com.github.mxsm.serialization.protobuf.TerminalType getTermType() {
      @SuppressWarnings("deprecation")
      com.github.mxsm.serialization.protobuf.TerminalType result = com.github.mxsm.serialization.protobuf.TerminalType.valueOf(termType_);
      return result == null ? com.github.mxsm.serialization.protobuf.TerminalType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * 终端类型，可能取值：Android, ios, web, DesktopApp, TestClient
     * </pre>
     *
     * <code>.com.github.mxsm.serialization.protobuf.TerminalType termType = 1;</code>
     * @param value The termType to set.
     * @return This builder for chaining.
     */
    public Builder setTermType(com.github.mxsm.serialization.protobuf.TerminalType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      termType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 终端类型，可能取值：Android, ios, web, DesktopApp, TestClient
     * </pre>
     *
     * <code>.com.github.mxsm.serialization.protobuf.TerminalType termType = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTermType() {
      
      termType_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object deviceType_ = "";
    /**
     * <pre>
     * 设备型号，如华为P10, iPhoneX, iPad3, Chrome等
     * </pre>
     *
     * <code>string deviceType = 2;</code>
     * @return The deviceType.
     */
    public java.lang.String getDeviceType() {
      java.lang.Object ref = deviceType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deviceType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 设备型号，如华为P10, iPhoneX, iPad3, Chrome等
     * </pre>
     *
     * <code>string deviceType = 2;</code>
     * @return The bytes for deviceType.
     */
    public com.google.protobuf.ByteString
        getDeviceTypeBytes() {
      java.lang.Object ref = deviceType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 设备型号，如华为P10, iPhoneX, iPad3, Chrome等
     * </pre>
     *
     * <code>string deviceType = 2;</code>
     * @param value The deviceType to set.
     * @return This builder for chaining.
     */
    public Builder setDeviceType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      deviceType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 设备型号，如华为P10, iPhoneX, iPad3, Chrome等
     * </pre>
     *
     * <code>string deviceType = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDeviceType() {
      
      deviceType_ = getDefaultInstance().getDeviceType();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 设备型号，如华为P10, iPhoneX, iPad3, Chrome等
     * </pre>
     *
     * <code>string deviceType = 2;</code>
     * @param value The bytes for deviceType to set.
     * @return This builder for chaining.
     */
    public Builder setDeviceTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      deviceType_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object osType_ = "";
    /**
     * <pre>
     * 操作系统型号，如Android7.2, iOS11, Windows10等
     * </pre>
     *
     * <code>string osType = 3;</code>
     * @return The osType.
     */
    public java.lang.String getOsType() {
      java.lang.Object ref = osType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        osType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 操作系统型号，如Android7.2, iOS11, Windows10等
     * </pre>
     *
     * <code>string osType = 3;</code>
     * @return The bytes for osType.
     */
    public com.google.protobuf.ByteString
        getOsTypeBytes() {
      java.lang.Object ref = osType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        osType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 操作系统型号，如Android7.2, iOS11, Windows10等
     * </pre>
     *
     * <code>string osType = 3;</code>
     * @param value The osType to set.
     * @return This builder for chaining.
     */
    public Builder setOsType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      osType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 操作系统型号，如Android7.2, iOS11, Windows10等
     * </pre>
     *
     * <code>string osType = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearOsType() {
      
      osType_ = getDefaultInstance().getOsType();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 操作系统型号，如Android7.2, iOS11, Windows10等
     * </pre>
     *
     * <code>string osType = 3;</code>
     * @param value The bytes for osType to set.
     * @return This builder for chaining.
     */
    public Builder setOsTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      osType_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object deviceToken_ = "";
    /**
     * <pre>
     * 设备编码
     * </pre>
     *
     * <code>string deviceToken = 4;</code>
     * @return The deviceToken.
     */
    public java.lang.String getDeviceToken() {
      java.lang.Object ref = deviceToken_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deviceToken_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 设备编码
     * </pre>
     *
     * <code>string deviceToken = 4;</code>
     * @return The bytes for deviceToken.
     */
    public com.google.protobuf.ByteString
        getDeviceTokenBytes() {
      java.lang.Object ref = deviceToken_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 设备编码
     * </pre>
     *
     * <code>string deviceToken = 4;</code>
     * @param value The deviceToken to set.
     * @return This builder for chaining.
     */
    public Builder setDeviceToken(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      deviceToken_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 设备编码
     * </pre>
     *
     * <code>string deviceToken = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearDeviceToken() {
      
      deviceToken_ = getDefaultInstance().getDeviceToken();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 设备编码
     * </pre>
     *
     * <code>string deviceToken = 4;</code>
     * @param value The bytes for deviceToken to set.
     * @return This builder for chaining.
     */
    public Builder setDeviceTokenBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      deviceToken_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.github.mxsm.serialization.protobuf.Terminal)
  }

  // @@protoc_insertion_point(class_scope:com.github.mxsm.serialization.protobuf.Terminal)
  private static final com.github.mxsm.serialization.protobuf.Terminal DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.github.mxsm.serialization.protobuf.Terminal();
  }

  public static com.github.mxsm.serialization.protobuf.Terminal getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Terminal>
      PARSER = new com.google.protobuf.AbstractParser<Terminal>() {
    @java.lang.Override
    public Terminal parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Terminal(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Terminal> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Terminal> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.github.mxsm.serialization.protobuf.Terminal getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

