// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AntMessage.proto

package com.github.mxsm.serialization.protobuf;

public interface TerminalOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.github.mxsm.serialization.protobuf.Terminal)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 终端类型，可能取值：Android, ios, web, DesktopApp, TestClient
   * </pre>
   *
   * <code>.com.github.mxsm.serialization.protobuf.TerminalType termType = 1;</code>
   * @return The enum numeric value on the wire for termType.
   */
  int getTermTypeValue();
  /**
   * <pre>
   * 终端类型，可能取值：Android, ios, web, DesktopApp, TestClient
   * </pre>
   *
   * <code>.com.github.mxsm.serialization.protobuf.TerminalType termType = 1;</code>
   * @return The termType.
   */
  com.github.mxsm.serialization.protobuf.TerminalType getTermType();

  /**
   * <pre>
   * 设备型号，如华为P10, iPhoneX, iPad3, Chrome等
   * </pre>
   *
   * <code>string deviceType = 2;</code>
   * @return The deviceType.
   */
  java.lang.String getDeviceType();
  /**
   * <pre>
   * 设备型号，如华为P10, iPhoneX, iPad3, Chrome等
   * </pre>
   *
   * <code>string deviceType = 2;</code>
   * @return The bytes for deviceType.
   */
  com.google.protobuf.ByteString
      getDeviceTypeBytes();

  /**
   * <pre>
   * 操作系统型号，如Android7.2, iOS11, Windows10等
   * </pre>
   *
   * <code>string osType = 3;</code>
   * @return The osType.
   */
  java.lang.String getOsType();
  /**
   * <pre>
   * 操作系统型号，如Android7.2, iOS11, Windows10等
   * </pre>
   *
   * <code>string osType = 3;</code>
   * @return The bytes for osType.
   */
  com.google.protobuf.ByteString
      getOsTypeBytes();

  /**
   * <pre>
   * 设备编码
   * </pre>
   *
   * <code>string deviceToken = 4;</code>
   * @return The deviceToken.
   */
  java.lang.String getDeviceToken();
  /**
   * <pre>
   * 设备编码
   * </pre>
   *
   * <code>string deviceToken = 4;</code>
   * @return The bytes for deviceToken.
   */
  com.google.protobuf.ByteString
      getDeviceTokenBytes();
}
