// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AntMessage.proto

package com.github.mxsm.serialization.protobuf;

public interface UserMetadataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.github.mxsm.serialization.protobuf.UserMetadata)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 用户ID
   * </pre>
   *
   * <code>int64 userId = 1;</code>
   * @return The userId.
   */
  long getUserId();

  /**
   * <pre>
   * 登录token
   * </pre>
   *
   * <code>string userToken = 2;</code>
   * @return The userToken.
   */
  java.lang.String getUserToken();
  /**
   * <pre>
   * 登录token
   * </pre>
   *
   * <code>string userToken = 2;</code>
   * @return The bytes for userToken.
   */
  com.google.protobuf.ByteString
      getUserTokenBytes();

  /**
   * <pre>
   * 当前用户组织ID
   * </pre>
   *
   * <code>int64 orgId = 3;</code>
   * @return The orgId.
   */
  long getOrgId();

  /**
   * <pre>
   * 当前用户名称
   * </pre>
   *
   * <code>string userName = 4;</code>
   * @return The userName.
   */
  java.lang.String getUserName();
  /**
   * <pre>
   * 当前用户名称
   * </pre>
   *
   * <code>string userName = 4;</code>
   * @return The bytes for userName.
   */
  com.google.protobuf.ByteString
      getUserNameBytes();

  /**
   * <pre>
   * 每次连接后由服务端产生的一个唯一一次连接ID，在同一次socket连接过程中保持不变，服务端和客户端应各自记录该ID值，在一次socket过程中保持传输该值
   * 以每个用户作为一个命名空间
   * </pre>
   *
   * <code>int64 connId = 5;</code>
   * @return The connId.
   */
  long getConnId();

  /**
   * <pre>
   *拥有拓展
   * </pre>
   *
   * <code>map&lt;string, string&gt; ext = 6;</code>
   */
  int getExtCount();
  /**
   * <pre>
   *拥有拓展
   * </pre>
   *
   * <code>map&lt;string, string&gt; ext = 6;</code>
   */
  boolean containsExt(
      java.lang.String key);
  /**
   * Use {@link #getExtMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getExt();
  /**
   * <pre>
   *拥有拓展
   * </pre>
   *
   * <code>map&lt;string, string&gt; ext = 6;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getExtMap();
  /**
   * <pre>
   *拥有拓展
   * </pre>
   *
   * <code>map&lt;string, string&gt; ext = 6;</code>
   */

  java.lang.String getExtOrDefault(
      java.lang.String key,
      java.lang.String defaultValue);
  /**
   * <pre>
   *拥有拓展
   * </pre>
   *
   * <code>map&lt;string, string&gt; ext = 6;</code>
   */

  java.lang.String getExtOrThrow(
      java.lang.String key);
}
