// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AntMessage.proto

package com.github.mxsm.serialization.protobuf;

/**
 * <pre>
 * 用户信息消息体
 * </pre>
 *
 * Protobuf type {@code com.github.mxsm.serialization.protobuf.UserMetadata}
 */
public final class UserMetadata extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.github.mxsm.serialization.protobuf.UserMetadata)
    UserMetadataOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UserMetadata.newBuilder() to construct.
  private UserMetadata(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UserMetadata() {
    userToken_ = "";
    userName_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new UserMetadata();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private UserMetadata(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            userId_ = input.readInt64();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            userToken_ = s;
            break;
          }
          case 24: {

            orgId_ = input.readInt64();
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            userName_ = s;
            break;
          }
          case 40: {

            connId_ = input.readInt64();
            break;
          }
          case 50: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              ext_ = com.google.protobuf.MapField.newMapField(
                  ExtDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000001;
            }
            com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
            ext__ = input.readMessage(
                ExtDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            ext_.getMutableMap().put(
                ext__.getKey(), ext__.getValue());
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.github.mxsm.serialization.protobuf.AntMessage.internal_static_com_github_mxsm_serialization_protobuf_UserMetadata_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 6:
        return internalGetExt();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.github.mxsm.serialization.protobuf.AntMessage.internal_static_com_github_mxsm_serialization_protobuf_UserMetadata_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.github.mxsm.serialization.protobuf.UserMetadata.class, com.github.mxsm.serialization.protobuf.UserMetadata.Builder.class);
  }

  public static final int USERID_FIELD_NUMBER = 1;
  private long userId_;
  /**
   * <pre>
   * 用户ID
   * </pre>
   *
   * <code>int64 userId = 1;</code>
   * @return The userId.
   */
  @java.lang.Override
  public long getUserId() {
    return userId_;
  }

  public static final int USERTOKEN_FIELD_NUMBER = 2;
  private volatile java.lang.Object userToken_;
  /**
   * <pre>
   * 登录token
   * </pre>
   *
   * <code>string userToken = 2;</code>
   * @return The userToken.
   */
  @java.lang.Override
  public java.lang.String getUserToken() {
    java.lang.Object ref = userToken_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      userToken_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 登录token
   * </pre>
   *
   * <code>string userToken = 2;</code>
   * @return The bytes for userToken.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUserTokenBytes() {
    java.lang.Object ref = userToken_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userToken_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ORGID_FIELD_NUMBER = 3;
  private long orgId_;
  /**
   * <pre>
   * 当前用户组织ID
   * </pre>
   *
   * <code>int64 orgId = 3;</code>
   * @return The orgId.
   */
  @java.lang.Override
  public long getOrgId() {
    return orgId_;
  }

  public static final int USERNAME_FIELD_NUMBER = 4;
  private volatile java.lang.Object userName_;
  /**
   * <pre>
   * 当前用户名称
   * </pre>
   *
   * <code>string userName = 4;</code>
   * @return The userName.
   */
  @java.lang.Override
  public java.lang.String getUserName() {
    java.lang.Object ref = userName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      userName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 当前用户名称
   * </pre>
   *
   * <code>string userName = 4;</code>
   * @return The bytes for userName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUserNameBytes() {
    java.lang.Object ref = userName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CONNID_FIELD_NUMBER = 5;
  private long connId_;
  /**
   * <pre>
   * 每次连接后由服务端产生的一个唯一一次连接ID，在同一次socket连接过程中保持不变，服务端和客户端应各自记录该ID值，在一次socket过程中保持传输该值
   * 以每个用户作为一个命名空间
   * </pre>
   *
   * <code>int64 connId = 5;</code>
   * @return The connId.
   */
  @java.lang.Override
  public long getConnId() {
    return connId_;
  }

  public static final int EXT_FIELD_NUMBER = 6;
  private static final class ExtDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                com.github.mxsm.serialization.protobuf.AntMessage.internal_static_com_github_mxsm_serialization_protobuf_UserMetadata_ExtEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> ext_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetExt() {
    if (ext_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          ExtDefaultEntryHolder.defaultEntry);
    }
    return ext_;
  }

  public int getExtCount() {
    return internalGetExt().getMap().size();
  }
  /**
   * <pre>
   *拥有拓展
   * </pre>
   *
   * <code>map&lt;string, string&gt; ext = 6;</code>
   */

  @java.lang.Override
  public boolean containsExt(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    return internalGetExt().getMap().containsKey(key);
  }
  /**
   * Use {@link #getExtMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getExt() {
    return getExtMap();
  }
  /**
   * <pre>
   *拥有拓展
   * </pre>
   *
   * <code>map&lt;string, string&gt; ext = 6;</code>
   */
  @java.lang.Override

  public java.util.Map<java.lang.String, java.lang.String> getExtMap() {
    return internalGetExt().getMap();
  }
  /**
   * <pre>
   *拥有拓展
   * </pre>
   *
   * <code>map&lt;string, string&gt; ext = 6;</code>
   */
  @java.lang.Override

  public java.lang.String getExtOrDefault(
      java.lang.String key,
      java.lang.String defaultValue) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetExt().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <pre>
   *拥有拓展
   * </pre>
   *
   * <code>map&lt;string, string&gt; ext = 6;</code>
   */
  @java.lang.Override

  public java.lang.String getExtOrThrow(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetExt().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (userId_ != 0L) {
      output.writeInt64(1, userId_);
    }
    if (!getUserTokenBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, userToken_);
    }
    if (orgId_ != 0L) {
      output.writeInt64(3, orgId_);
    }
    if (!getUserNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, userName_);
    }
    if (connId_ != 0L) {
      output.writeInt64(5, connId_);
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetExt(),
        ExtDefaultEntryHolder.defaultEntry,
        6);
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (userId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, userId_);
    }
    if (!getUserTokenBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, userToken_);
    }
    if (orgId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, orgId_);
    }
    if (!getUserNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, userName_);
    }
    if (connId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, connId_);
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetExt().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      ext__ = ExtDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, ext__);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.github.mxsm.serialization.protobuf.UserMetadata)) {
      return super.equals(obj);
    }
    com.github.mxsm.serialization.protobuf.UserMetadata other = (com.github.mxsm.serialization.protobuf.UserMetadata) obj;

    if (getUserId()
        != other.getUserId()) return false;
    if (!getUserToken()
        .equals(other.getUserToken())) return false;
    if (getOrgId()
        != other.getOrgId()) return false;
    if (!getUserName()
        .equals(other.getUserName())) return false;
    if (getConnId()
        != other.getConnId()) return false;
    if (!internalGetExt().equals(
        other.internalGetExt())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + USERID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getUserId());
    hash = (37 * hash) + USERTOKEN_FIELD_NUMBER;
    hash = (53 * hash) + getUserToken().hashCode();
    hash = (37 * hash) + ORGID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getOrgId());
    hash = (37 * hash) + USERNAME_FIELD_NUMBER;
    hash = (53 * hash) + getUserName().hashCode();
    hash = (37 * hash) + CONNID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getConnId());
    if (!internalGetExt().getMap().isEmpty()) {
      hash = (37 * hash) + EXT_FIELD_NUMBER;
      hash = (53 * hash) + internalGetExt().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.github.mxsm.serialization.protobuf.UserMetadata parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.mxsm.serialization.protobuf.UserMetadata parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.mxsm.serialization.protobuf.UserMetadata parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.mxsm.serialization.protobuf.UserMetadata parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.mxsm.serialization.protobuf.UserMetadata parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.mxsm.serialization.protobuf.UserMetadata parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.mxsm.serialization.protobuf.UserMetadata parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.mxsm.serialization.protobuf.UserMetadata parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.mxsm.serialization.protobuf.UserMetadata parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.github.mxsm.serialization.protobuf.UserMetadata parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.mxsm.serialization.protobuf.UserMetadata parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.mxsm.serialization.protobuf.UserMetadata parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.github.mxsm.serialization.protobuf.UserMetadata prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 用户信息消息体
   * </pre>
   *
   * Protobuf type {@code com.github.mxsm.serialization.protobuf.UserMetadata}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.github.mxsm.serialization.protobuf.UserMetadata)
      com.github.mxsm.serialization.protobuf.UserMetadataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.mxsm.serialization.protobuf.AntMessage.internal_static_com_github_mxsm_serialization_protobuf_UserMetadata_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 6:
          return internalGetExt();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 6:
          return internalGetMutableExt();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.mxsm.serialization.protobuf.AntMessage.internal_static_com_github_mxsm_serialization_protobuf_UserMetadata_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.mxsm.serialization.protobuf.UserMetadata.class, com.github.mxsm.serialization.protobuf.UserMetadata.Builder.class);
    }

    // Construct using com.github.mxsm.serialization.protobuf.UserMetadata.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      userId_ = 0L;

      userToken_ = "";

      orgId_ = 0L;

      userName_ = "";

      connId_ = 0L;

      internalGetMutableExt().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.github.mxsm.serialization.protobuf.AntMessage.internal_static_com_github_mxsm_serialization_protobuf_UserMetadata_descriptor;
    }

    @java.lang.Override
    public com.github.mxsm.serialization.protobuf.UserMetadata getDefaultInstanceForType() {
      return com.github.mxsm.serialization.protobuf.UserMetadata.getDefaultInstance();
    }

    @java.lang.Override
    public com.github.mxsm.serialization.protobuf.UserMetadata build() {
      com.github.mxsm.serialization.protobuf.UserMetadata result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.github.mxsm.serialization.protobuf.UserMetadata buildPartial() {
      com.github.mxsm.serialization.protobuf.UserMetadata result = new com.github.mxsm.serialization.protobuf.UserMetadata(this);
      int from_bitField0_ = bitField0_;
      result.userId_ = userId_;
      result.userToken_ = userToken_;
      result.orgId_ = orgId_;
      result.userName_ = userName_;
      result.connId_ = connId_;
      result.ext_ = internalGetExt();
      result.ext_.makeImmutable();
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.github.mxsm.serialization.protobuf.UserMetadata) {
        return mergeFrom((com.github.mxsm.serialization.protobuf.UserMetadata)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.github.mxsm.serialization.protobuf.UserMetadata other) {
      if (other == com.github.mxsm.serialization.protobuf.UserMetadata.getDefaultInstance()) return this;
      if (other.getUserId() != 0L) {
        setUserId(other.getUserId());
      }
      if (!other.getUserToken().isEmpty()) {
        userToken_ = other.userToken_;
        onChanged();
      }
      if (other.getOrgId() != 0L) {
        setOrgId(other.getOrgId());
      }
      if (!other.getUserName().isEmpty()) {
        userName_ = other.userName_;
        onChanged();
      }
      if (other.getConnId() != 0L) {
        setConnId(other.getConnId());
      }
      internalGetMutableExt().mergeFrom(
          other.internalGetExt());
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.github.mxsm.serialization.protobuf.UserMetadata parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.github.mxsm.serialization.protobuf.UserMetadata) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long userId_ ;
    /**
     * <pre>
     * 用户ID
     * </pre>
     *
     * <code>int64 userId = 1;</code>
     * @return The userId.
     */
    @java.lang.Override
    public long getUserId() {
      return userId_;
    }
    /**
     * <pre>
     * 用户ID
     * </pre>
     *
     * <code>int64 userId = 1;</code>
     * @param value The userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserId(long value) {
      
      userId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 用户ID
     * </pre>
     *
     * <code>int64 userId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserId() {
      
      userId_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object userToken_ = "";
    /**
     * <pre>
     * 登录token
     * </pre>
     *
     * <code>string userToken = 2;</code>
     * @return The userToken.
     */
    public java.lang.String getUserToken() {
      java.lang.Object ref = userToken_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userToken_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 登录token
     * </pre>
     *
     * <code>string userToken = 2;</code>
     * @return The bytes for userToken.
     */
    public com.google.protobuf.ByteString
        getUserTokenBytes() {
      java.lang.Object ref = userToken_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 登录token
     * </pre>
     *
     * <code>string userToken = 2;</code>
     * @param value The userToken to set.
     * @return This builder for chaining.
     */
    public Builder setUserToken(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      userToken_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 登录token
     * </pre>
     *
     * <code>string userToken = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserToken() {
      
      userToken_ = getDefaultInstance().getUserToken();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 登录token
     * </pre>
     *
     * <code>string userToken = 2;</code>
     * @param value The bytes for userToken to set.
     * @return This builder for chaining.
     */
    public Builder setUserTokenBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      userToken_ = value;
      onChanged();
      return this;
    }

    private long orgId_ ;
    /**
     * <pre>
     * 当前用户组织ID
     * </pre>
     *
     * <code>int64 orgId = 3;</code>
     * @return The orgId.
     */
    @java.lang.Override
    public long getOrgId() {
      return orgId_;
    }
    /**
     * <pre>
     * 当前用户组织ID
     * </pre>
     *
     * <code>int64 orgId = 3;</code>
     * @param value The orgId to set.
     * @return This builder for chaining.
     */
    public Builder setOrgId(long value) {
      
      orgId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 当前用户组织ID
     * </pre>
     *
     * <code>int64 orgId = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearOrgId() {
      
      orgId_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object userName_ = "";
    /**
     * <pre>
     * 当前用户名称
     * </pre>
     *
     * <code>string userName = 4;</code>
     * @return The userName.
     */
    public java.lang.String getUserName() {
      java.lang.Object ref = userName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 当前用户名称
     * </pre>
     *
     * <code>string userName = 4;</code>
     * @return The bytes for userName.
     */
    public com.google.protobuf.ByteString
        getUserNameBytes() {
      java.lang.Object ref = userName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 当前用户名称
     * </pre>
     *
     * <code>string userName = 4;</code>
     * @param value The userName to set.
     * @return This builder for chaining.
     */
    public Builder setUserName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      userName_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 当前用户名称
     * </pre>
     *
     * <code>string userName = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserName() {
      
      userName_ = getDefaultInstance().getUserName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 当前用户名称
     * </pre>
     *
     * <code>string userName = 4;</code>
     * @param value The bytes for userName to set.
     * @return This builder for chaining.
     */
    public Builder setUserNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      userName_ = value;
      onChanged();
      return this;
    }

    private long connId_ ;
    /**
     * <pre>
     * 每次连接后由服务端产生的一个唯一一次连接ID，在同一次socket连接过程中保持不变，服务端和客户端应各自记录该ID值，在一次socket过程中保持传输该值
     * 以每个用户作为一个命名空间
     * </pre>
     *
     * <code>int64 connId = 5;</code>
     * @return The connId.
     */
    @java.lang.Override
    public long getConnId() {
      return connId_;
    }
    /**
     * <pre>
     * 每次连接后由服务端产生的一个唯一一次连接ID，在同一次socket连接过程中保持不变，服务端和客户端应各自记录该ID值，在一次socket过程中保持传输该值
     * 以每个用户作为一个命名空间
     * </pre>
     *
     * <code>int64 connId = 5;</code>
     * @param value The connId to set.
     * @return This builder for chaining.
     */
    public Builder setConnId(long value) {
      
      connId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 每次连接后由服务端产生的一个唯一一次连接ID，在同一次socket连接过程中保持不变，服务端和客户端应各自记录该ID值，在一次socket过程中保持传输该值
     * 以每个用户作为一个命名空间
     * </pre>
     *
     * <code>int64 connId = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearConnId() {
      
      connId_ = 0L;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> ext_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetExt() {
      if (ext_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ExtDefaultEntryHolder.defaultEntry);
      }
      return ext_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetMutableExt() {
      onChanged();;
      if (ext_ == null) {
        ext_ = com.google.protobuf.MapField.newMapField(
            ExtDefaultEntryHolder.defaultEntry);
      }
      if (!ext_.isMutable()) {
        ext_ = ext_.copy();
      }
      return ext_;
    }

    public int getExtCount() {
      return internalGetExt().getMap().size();
    }
    /**
     * <pre>
     *拥有拓展
     * </pre>
     *
     * <code>map&lt;string, string&gt; ext = 6;</code>
     */

    @java.lang.Override
    public boolean containsExt(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetExt().getMap().containsKey(key);
    }
    /**
     * Use {@link #getExtMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getExt() {
      return getExtMap();
    }
    /**
     * <pre>
     *拥有拓展
     * </pre>
     *
     * <code>map&lt;string, string&gt; ext = 6;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, java.lang.String> getExtMap() {
      return internalGetExt().getMap();
    }
    /**
     * <pre>
     *拥有拓展
     * </pre>
     *
     * <code>map&lt;string, string&gt; ext = 6;</code>
     */
    @java.lang.Override

    public java.lang.String getExtOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetExt().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     *拥有拓展
     * </pre>
     *
     * <code>map&lt;string, string&gt; ext = 6;</code>
     */
    @java.lang.Override

    public java.lang.String getExtOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetExt().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearExt() {
      internalGetMutableExt().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <pre>
     *拥有拓展
     * </pre>
     *
     * <code>map&lt;string, string&gt; ext = 6;</code>
     */

    public Builder removeExt(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableExt().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
    getMutableExt() {
      return internalGetMutableExt().getMutableMap();
    }
    /**
     * <pre>
     *拥有拓展
     * </pre>
     *
     * <code>map&lt;string, string&gt; ext = 6;</code>
     */
    public Builder putExt(
        java.lang.String key,
        java.lang.String value) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      if (value == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableExt().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <pre>
     *拥有拓展
     * </pre>
     *
     * <code>map&lt;string, string&gt; ext = 6;</code>
     */

    public Builder putAllExt(
        java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableExt().getMutableMap()
          .putAll(values);
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.github.mxsm.serialization.protobuf.UserMetadata)
  }

  // @@protoc_insertion_point(class_scope:com.github.mxsm.serialization.protobuf.UserMetadata)
  private static final com.github.mxsm.serialization.protobuf.UserMetadata DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.github.mxsm.serialization.protobuf.UserMetadata();
  }

  public static com.github.mxsm.serialization.protobuf.UserMetadata getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UserMetadata>
      PARSER = new com.google.protobuf.AbstractParser<UserMetadata>() {
    @java.lang.Override
    public UserMetadata parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new UserMetadata(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<UserMetadata> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UserMetadata> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.github.mxsm.serialization.protobuf.UserMetadata getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

